;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/08/31 14:49:27
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;D-91_PIC16_color_changer_v-2.0.c,26 :: 		void main(void)
;D-91_PIC16_color_changer_v-2.0.c,30 :: 		TRISA     = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D-91_PIC16_color_changer_v-2.0.c,31 :: 		PORTA     = 0x00;		//0000 0010
$0007	$1283			BCF	STATUS, RP0
$0008	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-2.0.c,33 :: 		TRISB     = 0xFF;		// Input: RB0 ~ RB7
$0009	$30FF			MOVLW	255
$000A	$1683			BSF	STATUS, RP0
$000B	$0086			MOVWF	TRISB
;D-91_PIC16_color_changer_v-2.0.c,35 :: 		OPTION_REG &= 0x7F;	// Pull-up => on
$000C	$307F			MOVLW	127
$000D	$0581			ANDWF	OPTION_REG, 1
;D-91_PIC16_color_changer_v-2.0.c,37 :: 		while(1)
$000E	$	L_main_0:
;D-91_PIC16_color_changer_v-2.0.c,40 :: 		if (PORTB_0_H) {
$000E	$3001			MOVLW	1
$000F	$1283			BCF	STATUS, RP0
$0010	$0506			ANDWF	PORTB, 0
$0011	$00C0			MOVWF	STACK_0
$0012	$1903			BTFSC	STATUS, Z
$0013	$2817			GOTO	L_main_2
;D-91_PIC16_color_changer_v-2.0.c,42 :: 		LED_1_ON;
$0014	$3001			MOVLW	1
$0015	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-2.0.c,44 :: 		} else {
$0016	$2818			GOTO	L_main_3
$0017	$	L_main_2:
;D-91_PIC16_color_changer_v-2.0.c,46 :: 		LED_1_OFF;
$0017	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-2.0.c,48 :: 		}
$0018	$	L_main_3:
;D-91_PIC16_color_changer_v-2.0.c,50 :: 		}//while(1)
$0018	$280E			GOTO	L_main_0
;D-91_PIC16_color_changer_v-2.0.c,52 :: 		}//void main(void)
$0019	$2819			GOTO	$
