;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/07/26 16:49:30
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0033	$	__pulsing:
;D_85_Remote_v_5_4_0_Snd.c,57 :: 		void _pulsing(void)
;D_85_Remote_v_5_4_0_Snd.c,61 :: 		PORTA        = 0x01; Delay_ms(1);   // 8.8us
$0033	$3001			MOVLW	1
$0034	$1303			BCF	STATUS, RP1
$0035	$1283			BCF	STATUS, RP0
$0036	$0085			MOVWF	PORTA
$0037	$3007			MOVLW	7
$0038	$00CB			MOVWF	STACK_11
$0039	$30FF			MOVLW	255
$003A	$00CA			MOVWF	STACK_10
$003B	$0BCB			DECFSZ	STACK_11, F
$003C	$283E			GOTO	$+2
$003D	$2841			GOTO	$+4
$003E	$0BCA			DECFSZ	STACK_10, F
$003F	$283E			GOTO	$-1
$0040	$283B			GOTO	$-5
$0041	$3078			MOVLW	120
$0042	$00CA			MOVWF	STACK_10
$0043	$0BCA			DECFSZ	STACK_10, F
$0044	$2843			GOTO	$-1
$0045	$0000			NOP
$0046	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,63 :: 		PORTA        = 0x00; Delay_ms(1);
$0047	$0185			CLRF	PORTA, 1
$0048	$3007			MOVLW	7
$0049	$00CB			MOVWF	STACK_11
$004A	$30FF			MOVLW	255
$004B	$00CA			MOVWF	STACK_10
$004C	$0BCB			DECFSZ	STACK_11, F
$004D	$284F			GOTO	$+2
$004E	$2852			GOTO	$+4
$004F	$0BCA			DECFSZ	STACK_10, F
$0050	$284F			GOTO	$-1
$0051	$284C			GOTO	$-5
$0052	$3078			MOVLW	120
$0053	$00CA			MOVWF	STACK_10
$0054	$0BCA			DECFSZ	STACK_10, F
$0055	$2854			GOTO	$-1
$0056	$0000			NOP
$0057	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,65 :: 		}
$0058	$0008			RETURN
$007D	$	__pulsing_u_100:
;D_85_Remote_v_5_4_0_Snd.c,77 :: 		void _pulsing_u_100()
;D_85_Remote_v_5_4_0_Snd.c,80 :: 		PORTA = 0x01; Delay_us(100);
$007D	$3001			MOVLW	1
$007E	$1303			BCF	STATUS, RP1
$007F	$1283			BCF	STATUS, RP0
$0080	$0085			MOVWF	PORTA
$0081	$30A6			MOVLW	166
$0082	$00CA			MOVWF	STACK_10
$0083	$0BCA			DECFSZ	STACK_10, F
$0084	$2883			GOTO	$-1
$0085	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,82 :: 		PORTA = 0x00; Delay_us(100);
$0086	$0185			CLRF	PORTA, 1
$0087	$30A6			MOVLW	166
$0088	$00CA			MOVWF	STACK_10
$0089	$0BCA			DECFSZ	STACK_10, F
$008A	$2889			GOTO	$-1
$008B	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,84 :: 		}
$008C	$0008			RETURN
$0059	$	__pulsing_10ms:
;D_85_Remote_v_5_4_0_Snd.c,67 :: 		void _pulsing_10ms(void)
;D_85_Remote_v_5_4_0_Snd.c,71 :: 		PORTA        = 0x01; Delay_ms(10);   // 8.8us
$0059	$3001			MOVLW	1
$005A	$1303			BCF	STATUS, RP1
$005B	$1283			BCF	STATUS, RP0
$005C	$0085			MOVWF	PORTA
$005D	$3041			MOVLW	65
$005E	$00CB			MOVWF	STACK_11
$005F	$30FF			MOVLW	255
$0060	$00CA			MOVWF	STACK_10
$0061	$0BCB			DECFSZ	STACK_11, F
$0062	$2864			GOTO	$+2
$0063	$2867			GOTO	$+4
$0064	$0BCA			DECFSZ	STACK_10, F
$0065	$2864			GOTO	$-1
$0066	$2861			GOTO	$-5
$0067	$30C3			MOVLW	195
$0068	$00CA			MOVWF	STACK_10
$0069	$0BCA			DECFSZ	STACK_10, F
$006A	$2869			GOTO	$-1
$006B	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,73 :: 		PORTA        = 0x00; Delay_ms(10);
$006C	$0185			CLRF	PORTA, 1
$006D	$3041			MOVLW	65
$006E	$00CB			MOVWF	STACK_11
$006F	$30FF			MOVLW	255
$0070	$00CA			MOVWF	STACK_10
$0071	$0BCB			DECFSZ	STACK_11, F
$0072	$2874			GOTO	$+2
$0073	$2877			GOTO	$+4
$0074	$0BCA			DECFSZ	STACK_10, F
$0075	$2874			GOTO	$-1
$0076	$2871			GOTO	$-5
$0077	$30C3			MOVLW	195
$0078	$00CA			MOVWF	STACK_10
$0079	$0BCA			DECFSZ	STACK_10, F
$007A	$2879			GOTO	$-1
$007B	$0000			NOP
;D_85_Remote_v_5_4_0_Snd.c,75 :: 		}
$007C	$0008			RETURN
$008D	$	GlobalIniD_85_Remote_v_5_4_0_Snd:
$008D	$30FA			MOVLW	250
$008E	$1303			BCF	STATUS, RP1
$008F	$1283			BCF	STATUS, RP0
$0090	$008C			MOVWF	_custom_code_a+0
$0091	$3008			MOVLW	8
$0092	$008D			MOVWF	_bit_len+0
$0093	$0008			RETURN
$0004	$	_main:
;D_85_Remote_v_5_4_0_Snd.c,166 :: 		void main(void)
;D_85_Remote_v_5_4_0_Snd.c,173 :: 		TRISA     = 0x00;
$0004	$208D			CALL	GlobalIniD_85_Remote_v_5_4_0_Snd
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D_85_Remote_v_5_4_0_Snd.c,174 :: 		PORTA     = 0x00;		//0000 0010
$0007	$1283			BCF	STATUS, RP0
$0008	$0185			CLRF	PORTA, 1
;D_85_Remote_v_5_4_0_Snd.c,176 :: 		TRISB     = 0x00;		// Input: RB0 ~ RB7
$0009	$1683			BSF	STATUS, RP0
$000A	$0186			CLRF	TRISB, 1
;D_85_Remote_v_5_4_0_Snd.c,177 :: 		PORTB     = 0x00;
$000B	$1283			BCF	STATUS, RP0
$000C	$0186			CLRF	PORTB, 1
;D_85_Remote_v_5_4_0_Snd.c,179 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$000D	$30DF			MOVLW	223
$000E	$1683			BSF	STATUS, RP0
$000F	$0501			ANDWF	OPTION_REG, 0
$0010	$00C0			MOVWF	STACK_0
$0011	$0840			MOVF	STACK_0, 0
$0012	$0081			MOVWF	OPTION_REG
;D_85_Remote_v_5_4_0_Snd.c,180 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$0013	$30F0			MOVLW	240
$0014	$05C0			ANDWF	STACK_0, 1
$0015	$0840			MOVF	STACK_0, 0
$0016	$0081			MOVWF	OPTION_REG
;D_85_Remote_v_5_4_0_Snd.c,181 :: 		OPTION_REG |= 0x07;	// Prescaler => 1/256
$0017	$3007			MOVLW	7
$0018	$0440			IORWF	STACK_0, 0
$0019	$0081			MOVWF	OPTION_REG
;D_85_Remote_v_5_4_0_Snd.c,185 :: 		data_code_a   = 0x00;   // Button '+'
$001A	$018E			CLRF	_data_code_a, 1
;D_85_Remote_v_5_4_0_Snd.c,186 :: 		data_code_b   = ~data_code_a;
$001B	$30FF			MOVLW	255
$001C	$008F			MOVWF	_data_code_b
;D_85_Remote_v_5_4_0_Snd.c,188 :: 		while(1)
$001D	$	L_main_18:
;D_85_Remote_v_5_4_0_Snd.c,190 :: 		if((PORTB & 0x80) == 0x80)
$001D	$3080			MOVLW	128
$001E	$1283			BCF	STATUS, RP0
$001F	$0506			ANDWF	PORTB, 0
$0020	$00C1			MOVWF	STACK_1
$0021	$0841			MOVF	STACK_1, 0
$0022	$3A80			XORLW	128
$0023	$1D03			BTFSS	STATUS, Z
$0024	$2827			GOTO	L_main_20
;D_85_Remote_v_5_4_0_Snd.c,193 :: 		_pulsing();
$0025	$2033			CALL	__pulsing
;D_85_Remote_v_5_4_0_Snd.c,195 :: 		}
$0026	$2831			GOTO	L_main_21
$0027	$	L_main_20:
;D_85_Remote_v_5_4_0_Snd.c,196 :: 		else if((PORTB & 0x40) == 0x40)
$0027	$3040			MOVLW	64
$0028	$0506			ANDWF	PORTB, 0
$0029	$00C1			MOVWF	STACK_1
$002A	$0841			MOVF	STACK_1, 0
$002B	$3A40			XORLW	64
$002C	$1D03			BTFSS	STATUS, Z
$002D	$2830			GOTO	L_main_22
;D_85_Remote_v_5_4_0_Snd.c,199 :: 		_pulsing_u_100();
$002E	$207D			CALL	__pulsing_u_100
;D_85_Remote_v_5_4_0_Snd.c,201 :: 		}
$002F	$2831			GOTO	L_main_23
$0030	$	L_main_22:
;D_85_Remote_v_5_4_0_Snd.c,205 :: 		_pulsing_10ms();
$0030	$2059			CALL	__pulsing_10ms
;D_85_Remote_v_5_4_0_Snd.c,207 :: 		}
$0031	$	L_main_23:
$0031	$	L_main_21:
;D_85_Remote_v_5_4_0_Snd.c,223 :: 		}//while(1)
$0031	$281D			GOTO	L_main_18
;D_85_Remote_v_5_4_0_Snd.c,225 :: 		}//void main(void)
$0032	$2832			GOTO	$
