;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/02/22 16:42:04
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;D_80_16F84A_Chattering_v_2_0.c,1 :: 		void main(void)
;D_80_16F84A_Chattering_v_2_0.c,5 :: 		TRISA     = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D_80_16F84A_Chattering_v_2_0.c,6 :: 		PORTA     = 0x02;
$0007	$3002			MOVLW	2
$0008	$1283			BCF	STATUS, RP0
$0009	$0085			MOVWF	PORTA
;D_80_16F84A_Chattering_v_2_0.c,7 :: 		TRISB     = 0xFF;
$000A	$30FF			MOVLW	255
$000B	$1683			BSF	STATUS, RP0
$000C	$0086			MOVWF	TRISB
;D_80_16F84A_Chattering_v_2_0.c,9 :: 		OPTION_REG &= 0x7F;
$000D	$307F			MOVLW	127
$000E	$0581			ANDWF	OPTION_REG, 1
;D_80_16F84A_Chattering_v_2_0.c,11 :: 		rb0           = 1;
$000F	$3001			MOVLW	1
$0010	$008C			MOVWF	main_rb0_L0
;D_80_16F84A_Chattering_v_2_0.c,12 :: 		previous_rb0  = 1;
$0011	$3001			MOVLW	1
$0012	$008D			MOVWF	main_previous_rb0_L0
;D_80_16F84A_Chattering_v_2_0.c,14 :: 		while(1)
$0013	$	L_main_0:
;D_80_16F84A_Chattering_v_2_0.c,16 :: 		Delay_ms(20);
$0013	$3082			MOVLW	130
$0014	$00CB			MOVWF	STACK_11
$0015	$30FF			MOVLW	255
$0016	$00CA			MOVWF	STACK_10
$0017	$0BCB			DECFSZ	STACK_11, F
$0018	$281A			GOTO	$+2
$0019	$281D			GOTO	$+4
$001A	$0BCA			DECFSZ	STACK_10, F
$001B	$281A			GOTO	$-1
$001C	$2817			GOTO	$-5
$001D	$3087			MOVLW	135
$001E	$00CA			MOVWF	STACK_10
$001F	$0BCA			DECFSZ	STACK_10, F
$0020	$281F			GOTO	$-1
$0021	$0000			NOP
;D_80_16F84A_Chattering_v_2_0.c,18 :: 		rb0   = PORTB & 0x01;
$0022	$3001			MOVLW	1
$0023	$1283			BCF	STATUS, RP0
$0024	$0506			ANDWF	PORTB, 0
$0025	$00C1			MOVWF	STACK_1
$0026	$0841			MOVF	STACK_1, 0
$0027	$008C			MOVWF	main_rb0_L0
;D_80_16F84A_Chattering_v_2_0.c,20 :: 		if(rb0 == 0 && previous_rb0 == 1)
$0028	$0841			MOVF	STACK_1, 0
$0029	$3A00			XORLW	0
$002A	$1D03			BTFSS	STATUS, Z
$002B	$2832			GOTO	L_main_4
$002C	$080D			MOVF	main_previous_rb0_L0, 0
$002D	$3A01			XORLW	1
$002E	$1D03			BTFSS	STATUS, Z
$002F	$2832			GOTO	L_main_4
$0030	$	L36_ex_L_main_4:
;D_80_16F84A_Chattering_v_2_0.c,22 :: 		PORTA   ^= 0x03;
$0030	$3003			MOVLW	3
$0031	$0685			XORWF	PORTA, 1
;D_80_16F84A_Chattering_v_2_0.c,23 :: 		}
$0032	$	L_main_4:
;D_80_16F84A_Chattering_v_2_0.c,25 :: 		previous_rb0   = rb0;
$0032	$080C			MOVF	main_rb0_L0, 0
$0033	$008D			MOVWF	main_previous_rb0_L0
;D_80_16F84A_Chattering_v_2_0.c,27 :: 		}//while(1)
$0034	$2813			GOTO	L_main_0
;D_80_16F84A_Chattering_v_2_0.c,29 :: 		}//void main(void)
$0035	$2835			GOTO	$
