;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/07/18 15:09:43
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;D_85_16F84A_Remote_v_5_3_0.c,3 :: 		void main(void)
;D_85_16F84A_Remote_v_5_3_0.c,10 :: 		TRISA     = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D_85_16F84A_Remote_v_5_3_0.c,11 :: 		PORTA     = 0x00;		//0000 0010
$0007	$1283			BCF	STATUS, RP0
$0008	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,13 :: 		TRISB     = 0x00;		// Input: RB0 ~ RB7
$0009	$1683			BSF	STATUS, RP0
$000A	$0186			CLRF	TRISB, 1
;D_85_16F84A_Remote_v_5_3_0.c,14 :: 		PORTB     = 0x00;
$000B	$1283			BCF	STATUS, RP0
$000C	$0186			CLRF	PORTB, 1
;D_85_16F84A_Remote_v_5_3_0.c,16 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$000D	$30DF			MOVLW	223
$000E	$1683			BSF	STATUS, RP0
$000F	$0501			ANDWF	OPTION_REG, 0
$0010	$00C0			MOVWF	STACK_0
$0011	$0840			MOVF	STACK_0, 0
$0012	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,17 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$0013	$30F0			MOVLW	240
$0014	$05C0			ANDWF	STACK_0, 1
$0015	$0840			MOVF	STACK_0, 0
$0016	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,18 :: 		OPTION_REG |= 0x07;	// Prescaler => 1/256
$0017	$3007			MOVLW	7
$0018	$0440			IORWF	STACK_0, 0
$0019	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,25 :: 		while(1)
$001A	$	L_main_0:
;D_85_16F84A_Remote_v_5_3_0.c,30 :: 		TMR0     = 0;
$001A	$1283			BCF	STATUS, RP0
$001B	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_0.c,32 :: 		while(TMR0 < 176)         // 9.0ms
$001C	$	L_main_2:
$001C	$30B0			MOVLW	176
$001D	$0201			SUBWF	TMR0, 0
$001E	$1803			BTFSC	STATUS, C
$001F	$282E			GOTO	L_main_3
;D_85_16F84A_Remote_v_5_3_0.c,35 :: 		PORTA        = 0x01;   // RA0 => on
$0020	$3001			MOVLW	1
$0021	$0085			MOVWF	PORTA
;D_85_16F84A_Remote_v_5_3_0.c,36 :: 		Delay_us(9);   // 8.8us
$0022	$300E			MOVLW	14
$0023	$00CA			MOVWF	STACK_10
$0024	$0BCA			DECFSZ	STACK_10, F
$0025	$2824			GOTO	$-1
$0026	$0000			NOP
$0027	$0000			NOP
;D_85_16F84A_Remote_v_5_3_0.c,38 :: 		PORTA        = 0x00;   // RA0 => off
$0028	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,39 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$0029	$301C			MOVLW	28
$002A	$00CA			MOVWF	STACK_10
$002B	$0BCA			DECFSZ	STACK_10, F
$002C	$282B			GOTO	$-1
;D_85_16F84A_Remote_v_5_3_0.c,41 :: 		}
$002D	$281C			GOTO	L_main_2
$002E	$	L_main_3:
;D_85_16F84A_Remote_v_5_3_0.c,43 :: 		TMR0 = 0;
$002E	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_0.c,44 :: 		PORTA = 0x00;
$002F	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,46 :: 		while(TMR0 < 88)       // 4.5ms
$0030	$	L_main_4:
$0030	$3058			MOVLW	88
$0031	$0201			SUBWF	TMR0, 0
$0032	$1C03			BTFSS	STATUS, C
$0033	$2830			GOTO	L_main_4
;D_85_16F84A_Remote_v_5_3_0.c,49 :: 		}
$0034	$	L_main_5:
;D_85_16F84A_Remote_v_5_3_0.c,59 :: 		}//while(1)
$0034	$281A			GOTO	L_main_0
;D_85_16F84A_Remote_v_5_3_0.c,61 :: 		}//void main(void)
$0035	$2835			GOTO	$
