;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/07/18 16:12:13
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2820			GOTO	_main
$0004	$	__reader:
;D_85_16F84A_Remote_v_5_3_0.c,6 :: 		void _reader(void)
;D_85_16F84A_Remote_v_5_3_0.c,9 :: 		TMR0     = 0;
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_0.c,13 :: 		while(MS90)         // 9.0ms
$0007	$	L__reader_0:
$0007	$30B0			MOVLW	176
$0008	$0201			SUBWF	TMR0, 0
$0009	$1803			BTFSC	STATUS, C
$000A	$2819			GOTO	L__reader_1
;D_85_16F84A_Remote_v_5_3_0.c,16 :: 		PORTA        = 0x01;   // RA0 => on
$000B	$3001			MOVLW	1
$000C	$0085			MOVWF	PORTA
;D_85_16F84A_Remote_v_5_3_0.c,17 :: 		Delay_us(9);   // 8.8us
$000D	$300E			MOVLW	14
$000E	$00CA			MOVWF	STACK_10
$000F	$0BCA			DECFSZ	STACK_10, F
$0010	$280F			GOTO	$-1
$0011	$0000			NOP
$0012	$0000			NOP
;D_85_16F84A_Remote_v_5_3_0.c,19 :: 		PORTA        = 0x00;   // RA0 => off
$0013	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,20 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$0014	$301C			MOVLW	28
$0015	$00CA			MOVWF	STACK_10
$0016	$0BCA			DECFSZ	STACK_10, F
$0017	$2816			GOTO	$-1
;D_85_16F84A_Remote_v_5_3_0.c,22 :: 		}
$0018	$2807			GOTO	L__reader_0
$0019	$	L__reader_1:
;D_85_16F84A_Remote_v_5_3_0.c,24 :: 		TMR0 = 0;
$0019	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_0.c,25 :: 		PORTA = 0x00;
$001A	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,27 :: 		while(MS45)       // 4.5ms
$001B	$	L__reader_2:
$001B	$3058			MOVLW	88
$001C	$0201			SUBWF	TMR0, 0
$001D	$1C03			BTFSS	STATUS, C
$001E	$281B			GOTO	L__reader_2
;D_85_16F84A_Remote_v_5_3_0.c,31 :: 		}
$001F	$	L__reader_3:
;D_85_16F84A_Remote_v_5_3_0.c,33 :: 		}//void _reader(void)
$001F	$0008			RETURN
$0020	$	_main:
;D_85_16F84A_Remote_v_5_3_0.c,35 :: 		void main(void)
;D_85_16F84A_Remote_v_5_3_0.c,42 :: 		TRISA     = 0x00;
$0020	$1303			BCF	STATUS, RP1
$0021	$1683			BSF	STATUS, RP0
$0022	$0185			CLRF	TRISA, 1
;D_85_16F84A_Remote_v_5_3_0.c,43 :: 		PORTA     = 0x00;		//0000 0010
$0023	$1283			BCF	STATUS, RP0
$0024	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_0.c,45 :: 		TRISB     = 0x00;		// Input: RB0 ~ RB7
$0025	$1683			BSF	STATUS, RP0
$0026	$0186			CLRF	TRISB, 1
;D_85_16F84A_Remote_v_5_3_0.c,46 :: 		PORTB     = 0x00;
$0027	$1283			BCF	STATUS, RP0
$0028	$0186			CLRF	PORTB, 1
;D_85_16F84A_Remote_v_5_3_0.c,48 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$0029	$30DF			MOVLW	223
$002A	$1683			BSF	STATUS, RP0
$002B	$0501			ANDWF	OPTION_REG, 0
$002C	$00C0			MOVWF	STACK_0
$002D	$0840			MOVF	STACK_0, 0
$002E	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,49 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$002F	$30F0			MOVLW	240
$0030	$05C0			ANDWF	STACK_0, 1
$0031	$0840			MOVF	STACK_0, 0
$0032	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,50 :: 		OPTION_REG |= 0x07;	// Prescaler => 1/256
$0033	$3007			MOVLW	7
$0034	$0440			IORWF	STACK_0, 0
$0035	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_0.c,57 :: 		while(1)
$0036	$	L_main_4:
;D_85_16F84A_Remote_v_5_3_0.c,62 :: 		_reader();
$0036	$2004			CALL	__reader
;D_85_16F84A_Remote_v_5_3_0.c,93 :: 		}//while(1)
$0037	$2836			GOTO	L_main_4
;D_85_16F84A_Remote_v_5_3_0.c,95 :: 		}//void main(void)
$0038	$2838			GOTO	$
