;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/02/21 21:15:22
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0032	$	_buzzer:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,1 :: 		void buzzer(unsigned short int us)
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,5 :: 		PORTA    = 0x00;
$0032	$1303			BCF	STATUS, RP1
$0033	$1283			BCF	STATUS, RP0
$0034	$0185			CLRF	PORTA, 1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,7 :: 		for(i = 0; i < us; i++)
$0035	$018D			CLRF	buzzer_i_L0, 1
$0036	$	L_buzzer_0:
$0036	$080C			MOVF	FARG_buzzer+0, 0
$0037	$020D			SUBWF	buzzer_i_L0, 0
$0038	$1803			BTFSC	STATUS, C
$0039	$2841			GOTO	L_buzzer_1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,9 :: 		Delay_us(1);
$003A	$3001			MOVLW	1
$003B	$00CA			MOVWF	STACK_10
$003C	$0BCA			DECFSZ	STACK_10, F
$003D	$283C			GOTO	$-1
$003E	$0000			NOP
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,10 :: 		}
$003F	$	L_buzzer_2:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,7 :: 		for(i = 0; i < us; i++)
$003F	$0A8D			INCF	buzzer_i_L0, 1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,10 :: 		}
$0040	$2836			GOTO	L_buzzer_0
$0041	$	L_buzzer_1:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,12 :: 		PORTA = 0x01;
$0041	$3001			MOVLW	1
$0042	$0085			MOVWF	PORTA
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,14 :: 		for(i = 0; i < us; i++)
$0043	$018D			CLRF	buzzer_i_L0, 1
$0044	$	L_buzzer_3:
$0044	$080C			MOVF	FARG_buzzer+0, 0
$0045	$020D			SUBWF	buzzer_i_L0, 0
$0046	$1803			BTFSC	STATUS, C
$0047	$284F			GOTO	L_buzzer_4
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,16 :: 		Delay_us(1);
$0048	$3001			MOVLW	1
$0049	$00CA			MOVWF	STACK_10
$004A	$0BCA			DECFSZ	STACK_10, F
$004B	$284A			GOTO	$-1
$004C	$0000			NOP
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,17 :: 		}
$004D	$	L_buzzer_5:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,14 :: 		for(i = 0; i < us; i++)
$004D	$0A8D			INCF	buzzer_i_L0, 1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,17 :: 		}
$004E	$2844			GOTO	L_buzzer_3
$004F	$	L_buzzer_4:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,19 :: 		}//void buzzer(unsigned short int us)
$004F	$0008			RETURN
$0004	$	_main:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,21 :: 		void main(void)
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,23 :: 		TRISA     = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,24 :: 		PORTA     = 0x03;
$0007	$3003			MOVLW	3
$0008	$1283			BCF	STATUS, RP0
$0009	$0085			MOVWF	PORTA
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,25 :: 		TRISB     = 0xFF;
$000A	$30FF			MOVLW	255
$000B	$1683			BSF	STATUS, RP0
$000C	$0086			MOVWF	TRISB
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,27 :: 		OPTION_REG &= 0x7F;
$000D	$307F			MOVLW	127
$000E	$0581			ANDWF	OPTION_REG, 1
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,29 :: 		while(1)
$000F	$	L_main_6:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,31 :: 		switch(PORTB)
$000F	$1303			BCF	STATUS, RP1
$0010	$1683			BSF	STATUS, RP0
$0011	$2821			GOTO	L_main_8
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,33 :: 		case 0xFE : buzzer(239); break;/* 1111 1110 */
$0012	$	L_main_10:
$0012	$1303			BCF	STATUS, RP1
$0013	$1683			BSF	STATUS, RP0
$0014	$30EF			MOVLW	239
$0015	$008C			MOVWF	FARG_buzzer+0
$0016	$2032			CALL	_buzzer
$0017	$2830			GOTO	L_main_9
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,34 :: 		case 0xFD : buzzer(213); break;/* 1111 1101 */
$0018	$	L_main_11:
$0018	$30D5			MOVLW	213
$0019	$008C			MOVWF	FARG_buzzer+0
$001A	$2032			CALL	_buzzer
$001B	$2830			GOTO	L_main_9
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,35 :: 		case 0xFB : buzzer(190); break;/* 1111 1011 */
$001C	$	L_main_12:
$001C	$30BE			MOVLW	190
$001D	$008C			MOVWF	FARG_buzzer+0
$001E	$2032			CALL	_buzzer
$001F	$2830			GOTO	L_main_9
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,36 :: 		default   : break;
$0020	$	L_main_13:
$0020	$2830			GOTO	L_main_9
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,37 :: 		}
$0021	$	L_main_8:
$0021	$1303			BCF	STATUS, RP1
$0022	$1283			BCF	STATUS, RP0
$0023	$0806			MOVF	PORTB, 0
$0024	$3AFE			XORLW	254
$0025	$1903			BTFSC	STATUS, Z
$0026	$2812			GOTO	L_main_10
$0027	$0806			MOVF	PORTB, 0
$0028	$3AFD			XORLW	253
$0029	$1903			BTFSC	STATUS, Z
$002A	$2818			GOTO	L_main_11
$002B	$0806			MOVF	PORTB, 0
$002C	$3AFB			XORLW	251
$002D	$1903			BTFSC	STATUS, Z
$002E	$281C			GOTO	L_main_12
$002F	$2820			GOTO	L_main_13
$0030	$	L_main_9:
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,39 :: 		}//while(1)
$0030	$280F			GOTO	L_main_6
;D_79_PIC16F84A__Aoki_75_Buzzer_v-1.0.c,41 :: 		}//void main(void)
$0031	$2831			GOTO	$
