;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/09/01 11:30:10
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28D7			GOTO	_main
$0023	$	__Opearations:
;D-91_PIC16_color_changer_v-1.0.c,50 :: 		_Opearations() {
;D-91_PIC16_color_changer_v-1.0.c,52 :: 		while(PORTB_0_H) {
$0023	$	L__Opearations_0:
$0023	$3001			MOVLW	1
$0024	$1303			BCF	STATUS, RP1
$0025	$1283			BCF	STATUS, RP0
$0026	$0506			ANDWF	PORTB, 0
$0027	$00C1			MOVWF	STACK_1
$0028	$0841			MOVF	STACK_1, 0
$0029	$3A01			XORLW	1
$002A	$1D03			BTFSS	STATUS, Z
$002B	$28D6			GOTO	L__Opearations_1
;D-91_PIC16_color_changer_v-1.0.c,60 :: 		if ((PORTB_1_H) && (PORTB_2_H) && (PORTB_3_H)) {
$002C	$3002			MOVLW	2
$002D	$0506			ANDWF	PORTB, 0
$002E	$00C1			MOVWF	STACK_1
$002F	$0841			MOVF	STACK_1, 0
$0030	$3A02			XORLW	2
$0031	$1D03			BTFSS	STATUS, Z
$0032	$2844			GOTO	L__Opearations_4
$0033	$3004			MOVLW	4
$0034	$0506			ANDWF	PORTB, 0
$0035	$00C1			MOVWF	STACK_1
$0036	$0841			MOVF	STACK_1, 0
$0037	$3A04			XORLW	4
$0038	$1D03			BTFSS	STATUS, Z
$0039	$2844			GOTO	L__Opearations_4
$003A	$3008			MOVLW	8
$003B	$0506			ANDWF	PORTB, 0
$003C	$00C1			MOVWF	STACK_1
$003D	$0841			MOVF	STACK_1, 0
$003E	$3A08			XORLW	8
$003F	$1D03			BTFSS	STATUS, Z
$0040	$2844			GOTO	L__Opearations_4
$0041	$	L19_ex_L__Opearations_4:
;D-91_PIC16_color_changer_v-1.0.c,62 :: 		LEDs_ON;
$0041	$3007			MOVLW	7
$0042	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,69 :: 		} else if ((PORTB_1_H) && !(PORTB_2_H) && !(PORTB_3_H)) {
$0043	$28D5			GOTO	L__Opearations_5
$0044	$	L__Opearations_4:
$0044	$3002			MOVLW	2
$0045	$0506			ANDWF	PORTB, 0
$0046	$00C1			MOVWF	STACK_1
$0047	$0841			MOVF	STACK_1, 0
$0048	$3A02			XORLW	2
$0049	$1D03			BTFSS	STATUS, Z
$004A	$285C			GOTO	L__Opearations_8
$004B	$3004			MOVLW	4
$004C	$0506			ANDWF	PORTB, 0
$004D	$00C1			MOVWF	STACK_1
$004E	$0841			MOVF	STACK_1, 0
$004F	$3A04			XORLW	4
$0050	$1903			BTFSC	STATUS, Z
$0051	$285C			GOTO	L__Opearations_8
$0052	$3008			MOVLW	8
$0053	$0506			ANDWF	PORTB, 0
$0054	$00C1			MOVWF	STACK_1
$0055	$0841			MOVF	STACK_1, 0
$0056	$3A08			XORLW	8
$0057	$1903			BTFSC	STATUS, Z
$0058	$285C			GOTO	L__Opearations_8
$0059	$	L40_ex_L__Opearations_8:
;D-91_PIC16_color_changer_v-1.0.c,71 :: 		LED_1_ON;
$0059	$3001			MOVLW	1
$005A	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,73 :: 		} else if (!(PORTB_1_H) && (PORTB_2_H) && !(PORTB_3_H)) {
$005B	$28D5			GOTO	L__Opearations_9
$005C	$	L__Opearations_8:
$005C	$3002			MOVLW	2
$005D	$0506			ANDWF	PORTB, 0
$005E	$00C1			MOVWF	STACK_1
$005F	$0841			MOVF	STACK_1, 0
$0060	$3A02			XORLW	2
$0061	$1903			BTFSC	STATUS, Z
$0062	$2874			GOTO	L__Opearations_12
$0063	$3004			MOVLW	4
$0064	$0506			ANDWF	PORTB, 0
$0065	$00C1			MOVWF	STACK_1
$0066	$0841			MOVF	STACK_1, 0
$0067	$3A04			XORLW	4
$0068	$1D03			BTFSS	STATUS, Z
$0069	$2874			GOTO	L__Opearations_12
$006A	$3008			MOVLW	8
$006B	$0506			ANDWF	PORTB, 0
$006C	$00C1			MOVWF	STACK_1
$006D	$0841			MOVF	STACK_1, 0
$006E	$3A08			XORLW	8
$006F	$1903			BTFSC	STATUS, Z
$0070	$2874			GOTO	L__Opearations_12
$0071	$	L61_ex_L__Opearations_12:
;D-91_PIC16_color_changer_v-1.0.c,75 :: 		LED_2_ON;
$0071	$3002			MOVLW	2
$0072	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,77 :: 		} else if (!(PORTB_1_H) && !(PORTB_2_H) && (PORTB_3_H)) {
$0073	$28D5			GOTO	L__Opearations_13
$0074	$	L__Opearations_12:
$0074	$3002			MOVLW	2
$0075	$0506			ANDWF	PORTB, 0
$0076	$00C1			MOVWF	STACK_1
$0077	$0841			MOVF	STACK_1, 0
$0078	$3A02			XORLW	2
$0079	$1903			BTFSC	STATUS, Z
$007A	$288C			GOTO	L__Opearations_16
$007B	$3004			MOVLW	4
$007C	$0506			ANDWF	PORTB, 0
$007D	$00C1			MOVWF	STACK_1
$007E	$0841			MOVF	STACK_1, 0
$007F	$3A04			XORLW	4
$0080	$1903			BTFSC	STATUS, Z
$0081	$288C			GOTO	L__Opearations_16
$0082	$3008			MOVLW	8
$0083	$0506			ANDWF	PORTB, 0
$0084	$00C1			MOVWF	STACK_1
$0085	$0841			MOVF	STACK_1, 0
$0086	$3A08			XORLW	8
$0087	$1D03			BTFSS	STATUS, Z
$0088	$288C			GOTO	L__Opearations_16
$0089	$	L82_ex_L__Opearations_16:
;D-91_PIC16_color_changer_v-1.0.c,79 :: 		LED_3_ON;
$0089	$3004			MOVLW	4
$008A	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,86 :: 		} else if ((PORTB_1_H) && (PORTB_2_H) && !(PORTB_3_H)) {
$008B	$28D5			GOTO	L__Opearations_17
$008C	$	L__Opearations_16:
$008C	$3002			MOVLW	2
$008D	$0506			ANDWF	PORTB, 0
$008E	$00C1			MOVWF	STACK_1
$008F	$0841			MOVF	STACK_1, 0
$0090	$3A02			XORLW	2
$0091	$1D03			BTFSS	STATUS, Z
$0092	$28A4			GOTO	L__Opearations_20
$0093	$3004			MOVLW	4
$0094	$0506			ANDWF	PORTB, 0
$0095	$00C1			MOVWF	STACK_1
$0096	$0841			MOVF	STACK_1, 0
$0097	$3A04			XORLW	4
$0098	$1D03			BTFSS	STATUS, Z
$0099	$28A4			GOTO	L__Opearations_20
$009A	$3008			MOVLW	8
$009B	$0506			ANDWF	PORTB, 0
$009C	$00C1			MOVWF	STACK_1
$009D	$0841			MOVF	STACK_1, 0
$009E	$3A08			XORLW	8
$009F	$1903			BTFSC	STATUS, Z
$00A0	$28A4			GOTO	L__Opearations_20
$00A1	$	L102_ex_L__Opearations_20:
;D-91_PIC16_color_changer_v-1.0.c,88 :: 		LED_1_ON_2_ON;
$00A1	$3003			MOVLW	3
$00A2	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,90 :: 		} else if ((PORTB_1_H) && !(PORTB_2_H) && (PORTB_3_H)) {
$00A3	$28D5			GOTO	L__Opearations_21
$00A4	$	L__Opearations_20:
$00A4	$3002			MOVLW	2
$00A5	$0506			ANDWF	PORTB, 0
$00A6	$00C1			MOVWF	STACK_1
$00A7	$0841			MOVF	STACK_1, 0
$00A8	$3A02			XORLW	2
$00A9	$1D03			BTFSS	STATUS, Z
$00AA	$28BC			GOTO	L__Opearations_24
$00AB	$3004			MOVLW	4
$00AC	$0506			ANDWF	PORTB, 0
$00AD	$00C1			MOVWF	STACK_1
$00AE	$0841			MOVF	STACK_1, 0
$00AF	$3A04			XORLW	4
$00B0	$1903			BTFSC	STATUS, Z
$00B1	$28BC			GOTO	L__Opearations_24
$00B2	$3008			MOVLW	8
$00B3	$0506			ANDWF	PORTB, 0
$00B4	$00C1			MOVWF	STACK_1
$00B5	$0841			MOVF	STACK_1, 0
$00B6	$3A08			XORLW	8
$00B7	$1D03			BTFSS	STATUS, Z
$00B8	$28BC			GOTO	L__Opearations_24
$00B9	$	L122_ex_L__Opearations_24:
;D-91_PIC16_color_changer_v-1.0.c,92 :: 		LED_1_ON_3_ON;
$00B9	$3005			MOVLW	5
$00BA	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,94 :: 		} else if (!(PORTB_1_H) && (PORTB_2_H) && (PORTB_3_H)) {
$00BB	$28D5			GOTO	L__Opearations_25
$00BC	$	L__Opearations_24:
$00BC	$3002			MOVLW	2
$00BD	$0506			ANDWF	PORTB, 0
$00BE	$00C1			MOVWF	STACK_1
$00BF	$0841			MOVF	STACK_1, 0
$00C0	$3A02			XORLW	2
$00C1	$1903			BTFSC	STATUS, Z
$00C2	$28D4			GOTO	L__Opearations_28
$00C3	$3004			MOVLW	4
$00C4	$0506			ANDWF	PORTB, 0
$00C5	$00C1			MOVWF	STACK_1
$00C6	$0841			MOVF	STACK_1, 0
$00C7	$3A04			XORLW	4
$00C8	$1D03			BTFSS	STATUS, Z
$00C9	$28D4			GOTO	L__Opearations_28
$00CA	$3008			MOVLW	8
$00CB	$0506			ANDWF	PORTB, 0
$00CC	$00C1			MOVWF	STACK_1
$00CD	$0841			MOVF	STACK_1, 0
$00CE	$3A08			XORLW	8
$00CF	$1D03			BTFSS	STATUS, Z
$00D0	$28D4			GOTO	L__Opearations_28
$00D1	$	L142_ex_L__Opearations_28:
;D-91_PIC16_color_changer_v-1.0.c,96 :: 		LED_2_ON_3_ON;
$00D1	$3006			MOVLW	6
$00D2	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-1.0.c,103 :: 		} else {
$00D3	$28D5			GOTO	L__Opearations_29
$00D4	$	L__Opearations_28:
;D-91_PIC16_color_changer_v-1.0.c,105 :: 		LEDs_OFF;
$00D4	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-1.0.c,109 :: 		}
$00D5	$	L__Opearations_29:
$00D5	$	L__Opearations_25:
$00D5	$	L__Opearations_21:
$00D5	$	L__Opearations_17:
$00D5	$	L__Opearations_13:
$00D5	$	L__Opearations_9:
$00D5	$	L__Opearations_5:
;D-91_PIC16_color_changer_v-1.0.c,111 :: 		}//while(PORTB_0_H)
$00D5	$2823			GOTO	L__Opearations_0
$00D6	$	L__Opearations_1:
;D-91_PIC16_color_changer_v-1.0.c,113 :: 		}//_Opearations
$00D6	$0008			RETURN
$0004	$	_interrupt:
$0004	$00CF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$008D			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$008C			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$008E			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0840			MOVF	STACK_0, 0
$000E	$008F			MOVWF	STSAVED_0
;D-91_PIC16_color_changer_v-1.0.c,115 :: 		void interrupt(void)
;D-91_PIC16_color_changer_v-1.0.c,126 :: 		INTCON &= 0x7F;  // interrupt => forbidden
$000F	$307F			MOVLW	127
$0010	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-1.0.c,127 :: 		INTCON &= 0xEF;  // INT interrupt => forbidden
$0011	$30EF			MOVLW	239
$0012	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-1.0.c,128 :: 		INTCON &= 0xFD;  // INT interrupt flag => cleared
$0013	$30FD			MOVLW	253
$0014	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-1.0.c,130 :: 		_Opearations();
$0015	$2023			CALL	__Opearations
;D-91_PIC16_color_changer_v-1.0.c,138 :: 		INTCON |= 0x10;		  // INT interrupt => permitted
$0016	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-1.0.c,139 :: 		INTCON |= 0x80;
$0017	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-1.0.c,141 :: 		}//void interrupt(void)
$0018	$	L_Interrupt_end:
$0018	$080F			MOVF	STSAVED_0, 0
$0019	$00C0			MOVWF	STACK_0
$001A	$080E			MOVF	?savePCLATH, 0
$001B	$008A			MOVWF	PCLATH
$001C	$080C			MOVF	?saveFSR, 0
$001D	$0084			MOVWF	FSR
$001E	$0E0D			SWAPF	?saveSTATUS, 0
$001F	$0083			MOVWF	STATUS
$0020	$0ECF			SWAPF	STACK_15, 1
$0021	$0E4F			SWAPF	STACK_15, 0
$0022	$0009			RETFIE
$00D7	$	_main:
;D-91_PIC16_color_changer_v-1.0.c,144 :: 		void main(void)
;D-91_PIC16_color_changer_v-1.0.c,148 :: 		TRISA     = 0x00;
$00D7	$1303			BCF	STATUS, RP1
$00D8	$1683			BSF	STATUS, RP0
$00D9	$0185			CLRF	TRISA, 1
;D-91_PIC16_color_changer_v-1.0.c,149 :: 		PORTA     = 0x00;		//0000 0010
$00DA	$1283			BCF	STATUS, RP0
$00DB	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-1.0.c,151 :: 		TRISB     = 0xFF;		// Input: RB0 ~ RB7
$00DC	$30FF			MOVLW	255
$00DD	$1683			BSF	STATUS, RP0
$00DE	$0086			MOVWF	TRISB
;D-91_PIC16_color_changer_v-1.0.c,153 :: 		OPTION_REG &= 0x7F;	// Pull-up => on
$00DF	$307F			MOVLW	127
$00E0	$0501			ANDWF	OPTION_REG, 0
$00E1	$00C0			MOVWF	STACK_0
$00E2	$0840			MOVF	STACK_0, 0
$00E3	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-1.0.c,154 :: 		OPTION_REG &= 0xFF;	// INT interrupt => by 0V ~> 5V
$00E4	$30FF			MOVLW	255
$00E5	$0540			ANDWF	STACK_0, 0
$00E6	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-1.0.c,167 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$00E7	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-1.0.c,168 :: 		INTCON |= 0x80;
$00E8	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-1.0.c,170 :: 		while(1)
$00E9	$	L_main_30:
;D-91_PIC16_color_changer_v-1.0.c,174 :: 		LEDs_OFF;
$00E9	$1283			BCF	STATUS, RP0
$00EA	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-1.0.c,176 :: 		}//while(1)
$00EB	$28E9			GOTO	L_main_30
;D-91_PIC16_color_changer_v-1.0.c,178 :: 		}//void main(void)
$00EC	$28EC			GOTO	$
