;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/09/07 21:07:38
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28DB			GOTO	_main
$0119	$	__pulse_Modulation:
;D-91_PIC16_color_changer_v-3.1.c,75 :: 		_pulse_Modulation(void)
;D-91_PIC16_color_changer_v-3.1.c,79 :: 		PORTA        = 0x01;   // RA0 => on
$0119	$3001			MOVLW	1
$011A	$1303			BCF	STATUS, RP1
$011B	$1283			BCF	STATUS, RP0
$011C	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-3.1.c,80 :: 		Delay_us(9);   // 8.8us
$011D	$300E			MOVLW	14
$011E	$00CA			MOVWF	STACK_10
$011F	$0BCA			DECFSZ	STACK_10, F
$0120	$291F			GOTO	$-1
$0121	$0000			NOP
$0122	$0000			NOP
;D-91_PIC16_color_changer_v-3.1.c,82 :: 		PORTA        = 0x00;   // RA0 => off
$0123	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,83 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$0124	$301C			MOVLW	28
$0125	$00CA			MOVWF	STACK_10
$0126	$0BCA			DECFSZ	STACK_10, F
$0127	$2926			GOTO	$-1
;D-91_PIC16_color_changer_v-3.1.c,85 :: 		}
$0128	$0008			RETURN
$0129	$	__send_StopBit:
;D-91_PIC16_color_changer_v-3.1.c,401 :: 		void _send_StopBit(void) {
;D-91_PIC16_color_changer_v-3.1.c,403 :: 		RESET_TMR;
$0129	$1303			BCF	STATUS, RP1
$012A	$1283			BCF	STATUS, RP0
$012B	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.1.c,405 :: 		while(TMR0 < 11) {
$012C	$	L__send_StopBit_42:
$012C	$300B			MOVLW	11
$012D	$0201			SUBWF	TMR0, 0
$012E	$1803			BTFSC	STATUS, C
$012F	$2932			GOTO	L__send_StopBit_43
;D-91_PIC16_color_changer_v-3.1.c,407 :: 		_pulse_Modulation();
$0130	$2119			CALL	__pulse_Modulation
;D-91_PIC16_color_changer_v-3.1.c,409 :: 		}
$0131	$292C			GOTO	L__send_StopBit_42
$0132	$	L__send_StopBit_43:
;D-91_PIC16_color_changer_v-3.1.c,411 :: 		}
$0132	$0008			RETURN
$00B9	$	__Delay_50ms:
;D-91_PIC16_color_changer_v-3.1.c,225 :: 		_Delay_50ms(void) {
;D-91_PIC16_color_changer_v-3.1.c,227 :: 		Delay_ms(50);
$00B9	$3002			MOVLW	2
$00BA	$1303			BCF	STATUS, RP1
$00BB	$1283			BCF	STATUS, RP0
$00BC	$00CC			MOVWF	STACK_12
$00BD	$30FF			MOVLW	255
$00BE	$00CB			MOVWF	STACK_11
$00BF	$30FF			MOVLW	255
$00C0	$00CA			MOVWF	STACK_10
$00C1	$0BCC			DECFSZ	STACK_12, F
$00C2	$28C4			GOTO	$+2
$00C3	$28CB			GOTO	$+8
$00C4	$0BCB			DECFSZ	STACK_11, F
$00C5	$28C7			GOTO	$+2
$00C6	$28CA			GOTO	$+4
$00C7	$0BCA			DECFSZ	STACK_10, F
$00C8	$28C7			GOTO	$-1
$00C9	$28C4			GOTO	$-5
$00CA	$28C1			GOTO	$-9
$00CB	$3046			MOVLW	70
$00CC	$00CB			MOVWF	STACK_11
$00CD	$30FF			MOVLW	255
$00CE	$00CA			MOVWF	STACK_10
$00CF	$0BCB			DECFSZ	STACK_11, F
$00D0	$28D2			GOTO	$+2
$00D1	$28D5			GOTO	$+4
$00D2	$0BCA			DECFSZ	STACK_10, F
$00D3	$28D2			GOTO	$-1
$00D4	$28CF			GOTO	$-5
$00D5	$30CF			MOVLW	207
$00D6	$00CA			MOVWF	STACK_10
$00D7	$0BCA			DECFSZ	STACK_10, F
$00D8	$28D7			GOTO	$-1
$00D9	$0000			NOP
;D-91_PIC16_color_changer_v-3.1.c,229 :: 		}
$00DA	$0008			RETURN
$00FD	$	__reader:
;D-91_PIC16_color_changer_v-3.1.c,88 :: 		_reader(void)
;D-91_PIC16_color_changer_v-3.1.c,91 :: 		TMR0     = 0;
$00FD	$1303			BCF	STATUS, RP1
$00FE	$1283			BCF	STATUS, RP0
$00FF	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.1.c,95 :: 		while(MS90)         // 9.0ms
$0100	$	L__reader_0:
$0100	$30B0			MOVLW	176
$0101	$0201			SUBWF	TMR0, 0
$0102	$1803			BTFSC	STATUS, C
$0103	$2912			GOTO	L__reader_1
;D-91_PIC16_color_changer_v-3.1.c,98 :: 		PORTA        = 0x01;   // RA0 => on
$0104	$3001			MOVLW	1
$0105	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-3.1.c,99 :: 		Delay_us(9);   // 8.8us
$0106	$300E			MOVLW	14
$0107	$00CA			MOVWF	STACK_10
$0108	$0BCA			DECFSZ	STACK_10, F
$0109	$2908			GOTO	$-1
$010A	$0000			NOP
$010B	$0000			NOP
;D-91_PIC16_color_changer_v-3.1.c,101 :: 		PORTA        = 0x00;   // RA0 => off
$010C	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,102 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$010D	$301C			MOVLW	28
$010E	$00CA			MOVWF	STACK_10
$010F	$0BCA			DECFSZ	STACK_10, F
$0110	$290F			GOTO	$-1
;D-91_PIC16_color_changer_v-3.1.c,104 :: 		}
$0111	$2900			GOTO	L__reader_0
$0112	$	L__reader_1:
;D-91_PIC16_color_changer_v-3.1.c,106 :: 		TMR0 = 0;
$0112	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.1.c,107 :: 		PORTA = 0x00;
$0113	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,109 :: 		while(MS45)       // 4.5ms
$0114	$	L__reader_2:
$0114	$3058			MOVLW	88
$0115	$0201			SUBWF	TMR0, 0
$0116	$1C03			BTFSS	STATUS, C
$0117	$2914			GOTO	L__reader_2
;D-91_PIC16_color_changer_v-3.1.c,113 :: 		}
$0118	$	L__reader_3:
;D-91_PIC16_color_changer_v-3.1.c,115 :: 		}//void _reader(void)
$0118	$0008			RETURN
$0088	$	__custom_lower_num:
;D-91_PIC16_color_changer_v-3.1.c,171 :: 		_custom_lower_num(int code)
;D-91_PIC16_color_changer_v-3.1.c,174 :: 		bit_len = 4;
$0088	$3004			MOVLW	4
$0089	$1303			BCF	STATUS, RP1
$008A	$1283			BCF	STATUS, RP0
$008B	$008C			MOVWF	_bit_len
;D-91_PIC16_color_changer_v-3.1.c,176 :: 		custom_code_a = code;
$008C	$0812			MOVF	FARG__custom_lower_num+0, 0
$008D	$008D			MOVWF	_custom_code_a
;D-91_PIC16_color_changer_v-3.1.c,180 :: 		for(i = 0; i < bit_len; i++)
$008E	$018E			CLRF	_i, 1
$008F	$	L__custom_lower_num_15:
$008F	$080C			MOVF	_bit_len, 0
$0090	$020E			SUBWF	_i, 0
$0091	$1803			BTFSC	STATUS, C
$0092	$28B8			GOTO	L__custom_lower_num_16
;D-91_PIC16_color_changer_v-3.1.c,188 :: 		RESET_TMR;
$0093	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.1.c,190 :: 		while(TMR0 < 11)	// 0.56ms
$0094	$	L__custom_lower_num_18:
$0094	$300B			MOVLW	11
$0095	$0201			SUBWF	TMR0, 0
$0096	$1803			BTFSC	STATUS, C
$0097	$289A			GOTO	L__custom_lower_num_19
;D-91_PIC16_color_changer_v-3.1.c,192 :: 		_pulse_Modulation();
$0098	$2119			CALL	__pulse_Modulation
;D-91_PIC16_color_changer_v-3.1.c,194 :: 		}
$0099	$2894			GOTO	L__custom_lower_num_18
$009A	$	L__custom_lower_num_19:
;D-91_PIC16_color_changer_v-3.1.c,201 :: 		PORTA = 0x00;
$009A	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,203 :: 		if (((custom_code_a >> i) & 0x01) == 0)
$009B	$080E			MOVF	_i, 0
$009C	$00C1			MOVWF	STACK_1
$009D	$080D			MOVF	_custom_code_a, 0
$009E	$00C0			MOVWF	STACK_0
$009F	$0841			MOVF	STACK_1, 0
$00A0	$	L__custom_lower_num_46:
$00A0	$1903			BTFSC	STATUS, Z
$00A1	$28A6			GOTO	L__custom_lower_num_47
$00A2	$0CC0			RRF	STACK_0, 1
$00A3	$13C0			BCF	STACK_0, 7
$00A4	$3FFF			ADDLW	255
$00A5	$28A0			GOTO	L__custom_lower_num_46
$00A6	$	L__custom_lower_num_47:
$00A6	$3001			MOVLW	1
$00A7	$0540			ANDWF	STACK_0, 0
$00A8	$00C1			MOVWF	STACK_1
$00A9	$0841			MOVF	STACK_1, 0
$00AA	$3A00			XORLW	0
$00AB	$1D03			BTFSS	STATUS, Z
$00AC	$28B2			GOTO	L__custom_lower_num_20
;D-91_PIC16_color_changer_v-3.1.c,206 :: 		while(TMR0 < 22)	// 1.125ms
$00AD	$	L__custom_lower_num_21:
$00AD	$3016			MOVLW	22
$00AE	$0201			SUBWF	TMR0, 0
$00AF	$1C03			BTFSS	STATUS, C
$00B0	$28AD			GOTO	L__custom_lower_num_21
;D-91_PIC16_color_changer_v-3.1.c,209 :: 		}
$00B1	$	L__custom_lower_num_22:
;D-91_PIC16_color_changer_v-3.1.c,211 :: 		} else {
$00B1	$28B6			GOTO	L__custom_lower_num_23
$00B2	$	L__custom_lower_num_20:
;D-91_PIC16_color_changer_v-3.1.c,213 :: 		while(TMR0 < 44)	// 2.250ms
$00B2	$	L__custom_lower_num_24:
$00B2	$302C			MOVLW	44
$00B3	$0201			SUBWF	TMR0, 0
$00B4	$1C03			BTFSS	STATUS, C
$00B5	$28B2			GOTO	L__custom_lower_num_24
;D-91_PIC16_color_changer_v-3.1.c,216 :: 		}
$00B6	$	L__custom_lower_num_25:
;D-91_PIC16_color_changer_v-3.1.c,218 :: 		}//if (((custom_code_a >> i) & 0x01) == 0)
$00B6	$	L__custom_lower_num_23:
;D-91_PIC16_color_changer_v-3.1.c,220 :: 		}//for(i = 0; i < bit_len)
$00B6	$	L__custom_lower_num_17:
;D-91_PIC16_color_changer_v-3.1.c,180 :: 		for(i = 0; i < bit_len; i++)
$00B6	$0A8E			INCF	_i, 1
;D-91_PIC16_color_changer_v-3.1.c,220 :: 		}//for(i = 0; i < bit_len)
$00B7	$288F			GOTO	L__custom_lower_num_15
$00B8	$	L__custom_lower_num_16:
;D-91_PIC16_color_changer_v-3.1.c,222 :: 		}//_custom_lower
$00B8	$0008			RETURN
$0133	$	__Stop:
;D-91_PIC16_color_changer_v-3.1.c,413 :: 		void _Stop(void) {
;D-91_PIC16_color_changer_v-3.1.c,420 :: 		_send_StopBit();
$0133	$2129			CALL	__send_StopBit
;D-91_PIC16_color_changer_v-3.1.c,427 :: 		PORTA = 0x00;
$0134	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,435 :: 		_Delay_50ms();
$0135	$20B9			CALL	__Delay_50ms
;D-91_PIC16_color_changer_v-3.1.c,438 :: 		}//_Stop
$0136	$0008			RETURN
$0023	$	__Opearations:
;D-91_PIC16_color_changer_v-3.1.c,232 :: 		_Opearations() {
;D-91_PIC16_color_changer_v-3.1.c,234 :: 		while(PORTB_0_H) {
$0023	$	L__Opearations_26:
$0023	$3001			MOVLW	1
$0024	$1303			BCF	STATUS, RP1
$0025	$1283			BCF	STATUS, RP0
$0026	$0506			ANDWF	PORTB, 0
$0027	$00C1			MOVWF	STACK_1
$0028	$0841			MOVF	STACK_1, 0
$0029	$3A01			XORLW	1
$002A	$1D03			BTFSS	STATUS, Z
$002B	$2887			GOTO	L__Opearations_27
;D-91_PIC16_color_changer_v-3.1.c,242 :: 		if ((PORTB_1_H) && !(PORTB_2_H) && !(PORTB_3_H)) {
$002C	$3002			MOVLW	2
$002D	$0506			ANDWF	PORTB, 0
$002E	$00C1			MOVWF	STACK_1
$002F	$0841			MOVF	STACK_1, 0
$0030	$3A02			XORLW	2
$0031	$1D03			BTFSS	STATUS, Z
$0032	$284B			GOTO	L__Opearations_30
$0033	$3004			MOVLW	4
$0034	$0506			ANDWF	PORTB, 0
$0035	$00C1			MOVWF	STACK_1
$0036	$0841			MOVF	STACK_1, 0
$0037	$3A04			XORLW	4
$0038	$1903			BTFSC	STATUS, Z
$0039	$284B			GOTO	L__Opearations_30
$003A	$3008			MOVLW	8
$003B	$0506			ANDWF	PORTB, 0
$003C	$00C1			MOVWF	STACK_1
$003D	$0841			MOVF	STACK_1, 0
$003E	$3A08			XORLW	8
$003F	$1903			BTFSC	STATUS, Z
$0040	$284B			GOTO	L__Opearations_30
$0041	$	L156_ex_L__Opearations_30:
;D-91_PIC16_color_changer_v-3.1.c,244 :: 		_reader();
$0041	$20FD			CALL	__reader
;D-91_PIC16_color_changer_v-3.1.c,247 :: 		_custom_lower_num(15);
$0042	$300F			MOVLW	15
$0043	$0092			MOVWF	FARG__custom_lower_num+0
$0044	$3000			MOVLW	0
$0045	$0093			MOVWF	FARG__custom_lower_num+1
$0046	$2088			CALL	__custom_lower_num
;D-91_PIC16_color_changer_v-3.1.c,256 :: 		_send_StopBit();
$0047	$2129			CALL	__send_StopBit
;D-91_PIC16_color_changer_v-3.1.c,263 :: 		PORTA = 0x00;
$0048	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,271 :: 		_Delay_50ms();
$0049	$20B9			CALL	__Delay_50ms
;D-91_PIC16_color_changer_v-3.1.c,273 :: 		} else if (!(PORTB_1_H) && (PORTB_2_H) && !(PORTB_3_H)) {
$004A	$2886			GOTO	L__Opearations_31
$004B	$	L__Opearations_30:
$004B	$3002			MOVLW	2
$004C	$0506			ANDWF	PORTB, 0
$004D	$00C1			MOVWF	STACK_1
$004E	$0841			MOVF	STACK_1, 0
$004F	$3A02			XORLW	2
$0050	$1903			BTFSC	STATUS, Z
$0051	$2868			GOTO	L__Opearations_34
$0052	$3004			MOVLW	4
$0053	$0506			ANDWF	PORTB, 0
$0054	$00C1			MOVWF	STACK_1
$0055	$0841			MOVF	STACK_1, 0
$0056	$3A04			XORLW	4
$0057	$1D03			BTFSS	STATUS, Z
$0058	$2868			GOTO	L__Opearations_34
$0059	$3008			MOVLW	8
$005A	$0506			ANDWF	PORTB, 0
$005B	$00C1			MOVWF	STACK_1
$005C	$0841			MOVF	STACK_1, 0
$005D	$3A08			XORLW	8
$005E	$1903			BTFSC	STATUS, Z
$005F	$2868			GOTO	L__Opearations_34
$0060	$	L182_ex_L__Opearations_34:
;D-91_PIC16_color_changer_v-3.1.c,275 :: 		_reader();
$0060	$20FD			CALL	__reader
;D-91_PIC16_color_changer_v-3.1.c,277 :: 		_custom_lower_num(8);
$0061	$3008			MOVLW	8
$0062	$0092			MOVWF	FARG__custom_lower_num+0
$0063	$3000			MOVLW	0
$0064	$0093			MOVWF	FARG__custom_lower_num+1
$0065	$2088			CALL	__custom_lower_num
;D-91_PIC16_color_changer_v-3.1.c,279 :: 		_Stop();
$0066	$2133			CALL	__Stop
;D-91_PIC16_color_changer_v-3.1.c,287 :: 		} else if (!(PORTB_1_H) && !(PORTB_2_H) && (PORTB_3_H)) {
$0067	$2886			GOTO	L__Opearations_35
$0068	$	L__Opearations_34:
$0068	$3002			MOVLW	2
$0069	$0506			ANDWF	PORTB, 0
$006A	$00C1			MOVWF	STACK_1
$006B	$0841			MOVF	STACK_1, 0
$006C	$3A02			XORLW	2
$006D	$1903			BTFSC	STATUS, Z
$006E	$2885			GOTO	L__Opearations_38
$006F	$3004			MOVLW	4
$0070	$0506			ANDWF	PORTB, 0
$0071	$00C1			MOVWF	STACK_1
$0072	$0841			MOVF	STACK_1, 0
$0073	$3A04			XORLW	4
$0074	$1903			BTFSC	STATUS, Z
$0075	$2885			GOTO	L__Opearations_38
$0076	$3008			MOVLW	8
$0077	$0506			ANDWF	PORTB, 0
$0078	$00C1			MOVWF	STACK_1
$0079	$0841			MOVF	STACK_1, 0
$007A	$3A08			XORLW	8
$007B	$1D03			BTFSS	STATUS, Z
$007C	$2885			GOTO	L__Opearations_38
$007D	$	L206_ex_L__Opearations_38:
;D-91_PIC16_color_changer_v-3.1.c,289 :: 		_reader();
$007D	$20FD			CALL	__reader
;D-91_PIC16_color_changer_v-3.1.c,291 :: 		_custom_lower_num(10);
$007E	$300A			MOVLW	10
$007F	$0092			MOVWF	FARG__custom_lower_num+0
$0080	$3000			MOVLW	0
$0081	$0093			MOVWF	FARG__custom_lower_num+1
$0082	$2088			CALL	__custom_lower_num
;D-91_PIC16_color_changer_v-3.1.c,293 :: 		_Stop();
$0083	$2133			CALL	__Stop
;D-91_PIC16_color_changer_v-3.1.c,301 :: 		} else {
$0084	$2886			GOTO	L__Opearations_39
$0085	$	L__Opearations_38:
;D-91_PIC16_color_changer_v-3.1.c,303 :: 		OUT_OFF;
$0085	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,305 :: 		}
$0086	$	L__Opearations_39:
$0086	$	L__Opearations_35:
$0086	$	L__Opearations_31:
;D-91_PIC16_color_changer_v-3.1.c,307 :: 		}//while(PORTB_0_H)
$0086	$2823			GOTO	L__Opearations_26
$0087	$	L__Opearations_27:
;D-91_PIC16_color_changer_v-3.1.c,323 :: 		}//_Opearations
$0087	$0008			RETURN
$0004	$	_interrupt:
$0004	$00CF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$0090			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$008F			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$0091			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0840			MOVF	STACK_0, 0
$000E	$0094			MOVWF	STSAVED_0
;D-91_PIC16_color_changer_v-3.1.c,325 :: 		void interrupt(void)
;D-91_PIC16_color_changer_v-3.1.c,336 :: 		INTCON &= 0x7F;  // interrupt => forbidden
$000F	$307F			MOVLW	127
$0010	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.1.c,337 :: 		INTCON &= 0xEF;  // INT interrupt => forbidden
$0011	$30EF			MOVLW	239
$0012	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.1.c,338 :: 		INTCON &= 0xFD;  // INT interrupt flag => cleared
$0013	$30FD			MOVLW	253
$0014	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.1.c,340 :: 		_Opearations();
$0015	$2023			CALL	__Opearations
;D-91_PIC16_color_changer_v-3.1.c,348 :: 		INTCON |= 0x10;		  // INT interrupt => permitted
$0016	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-3.1.c,349 :: 		INTCON |= 0x80;
$0017	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-3.1.c,351 :: 		}//void interrupt(void)
$0018	$	L_Interrupt_end:
$0018	$0814			MOVF	STSAVED_0, 0
$0019	$00C0			MOVWF	STACK_0
$001A	$0811			MOVF	?savePCLATH, 0
$001B	$008A			MOVWF	PCLATH
$001C	$080F			MOVF	?saveFSR, 0
$001D	$0084			MOVWF	FSR
$001E	$0E10			SWAPF	?saveSTATUS, 0
$001F	$0083			MOVWF	STATUS
$0020	$0ECF			SWAPF	STACK_15, 1
$0021	$0E4F			SWAPF	STACK_15, 0
$0022	$0009			RETFIE
$00DB	$	_main:
;D-91_PIC16_color_changer_v-3.1.c,354 :: 		void main(void)
;D-91_PIC16_color_changer_v-3.1.c,358 :: 		TRISA     = 0x00;
$00DB	$1303			BCF	STATUS, RP1
$00DC	$1683			BSF	STATUS, RP0
$00DD	$0185			CLRF	TRISA, 1
;D-91_PIC16_color_changer_v-3.1.c,359 :: 		PORTA     = 0x00;		//0000 0010
$00DE	$1283			BCF	STATUS, RP0
$00DF	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,361 :: 		TRISB     = 0xFF;		// Input: RB0 ~ RB7
$00E0	$30FF			MOVLW	255
$00E1	$1683			BSF	STATUS, RP0
$00E2	$0086			MOVWF	TRISB
;D-91_PIC16_color_changer_v-3.1.c,363 :: 		OPTION_REG &= 0x7F;	// Pull-up => on
$00E3	$307F			MOVLW	127
$00E4	$0501			ANDWF	OPTION_REG, 0
$00E5	$00C0			MOVWF	STACK_0
$00E6	$0840			MOVF	STACK_0, 0
$00E7	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.1.c,364 :: 		OPTION_REG &= 0xFF;	// INT interrupt => by 0V ~> 5V
$00E8	$30FF			MOVLW	255
$00E9	$05C0			ANDWF	STACK_0, 1
$00EA	$0840			MOVF	STACK_0, 0
$00EB	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.1.c,367 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$00EC	$30DF			MOVLW	223
$00ED	$05C0			ANDWF	STACK_0, 1
$00EE	$0840			MOVF	STACK_0, 0
$00EF	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.1.c,368 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$00F0	$30F0			MOVLW	240
$00F1	$05C0			ANDWF	STACK_0, 1
$00F2	$0840			MOVF	STACK_0, 0
$00F3	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.1.c,369 :: 		OPTION_REG |= 0x07; // Prescaler => 1/256
$00F4	$3007			MOVLW	7
$00F5	$0440			IORWF	STACK_0, 0
$00F6	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.1.c,377 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$00F7	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-3.1.c,378 :: 		INTCON |= 0x80;
$00F8	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-3.1.c,380 :: 		while(1)
$00F9	$	L_main_40:
;D-91_PIC16_color_changer_v-3.1.c,383 :: 		OUT_OFF;
$00F9	$1283			BCF	STATUS, RP0
$00FA	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.1.c,385 :: 		}//while(1)
$00FB	$28F9			GOTO	L_main_40
;D-91_PIC16_color_changer_v-3.1.c,387 :: 		}//void main(void)
$00FC	$28FC			GOTO	$
