;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/02/22 16:35:28
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;D_80_16F84A_Chattering_v_1_0.c,1 :: 		void main(void)
;D_80_16F84A_Chattering_v_1_0.c,5 :: 		TRISA     = 0x00;
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0185			CLRF	TRISA, 1
;D_80_16F84A_Chattering_v_1_0.c,6 :: 		PORTA     = 0x02;
$0007	$3002			MOVLW	2
$0008	$1283			BCF	STATUS, RP0
$0009	$0085			MOVWF	PORTA
;D_80_16F84A_Chattering_v_1_0.c,7 :: 		TRISB     = 0xFF;
$000A	$30FF			MOVLW	255
$000B	$1683			BSF	STATUS, RP0
$000C	$0086			MOVWF	TRISB
;D_80_16F84A_Chattering_v_1_0.c,9 :: 		OPTION_REG &= 0x7F;
$000D	$307F			MOVLW	127
$000E	$0581			ANDWF	OPTION_REG, 1
;D_80_16F84A_Chattering_v_1_0.c,11 :: 		rb0           = 1;
$000F	$3001			MOVLW	1
$0010	$008C			MOVWF	main_rb0_L0
;D_80_16F84A_Chattering_v_1_0.c,12 :: 		previous_rb0  = 1;
$0011	$3001			MOVLW	1
$0012	$008D			MOVWF	main_previous_rb0_L0
;D_80_16F84A_Chattering_v_1_0.c,14 :: 		while(1)
$0013	$	L_main_0:
;D_80_16F84A_Chattering_v_1_0.c,16 :: 		rb0   = PORTB & 0x01;
$0013	$3001			MOVLW	1
$0014	$1283			BCF	STATUS, RP0
$0015	$0506			ANDWF	PORTB, 0
$0016	$00C1			MOVWF	STACK_1
$0017	$0841			MOVF	STACK_1, 0
$0018	$008C			MOVWF	main_rb0_L0
;D_80_16F84A_Chattering_v_1_0.c,18 :: 		if(rb0 == 0 && previous_rb0 == 1)
$0019	$0841			MOVF	STACK_1, 0
$001A	$3A00			XORLW	0
$001B	$1D03			BTFSS	STATUS, Z
$001C	$2823			GOTO	L_main_4
$001D	$080D			MOVF	main_previous_rb0_L0, 0
$001E	$3A01			XORLW	1
$001F	$1D03			BTFSS	STATUS, Z
$0020	$2823			GOTO	L_main_4
$0021	$	L21_ex_L_main_4:
;D_80_16F84A_Chattering_v_1_0.c,20 :: 		PORTA   ^= 0x03;
$0021	$3003			MOVLW	3
$0022	$0685			XORWF	PORTA, 1
;D_80_16F84A_Chattering_v_1_0.c,21 :: 		}
$0023	$	L_main_4:
;D_80_16F84A_Chattering_v_1_0.c,23 :: 		previous_rb0   = rb0;
$0023	$080C			MOVF	main_rb0_L0, 0
$0024	$008D			MOVWF	main_previous_rb0_L0
;D_80_16F84A_Chattering_v_1_0.c,25 :: 		}//while(1)
$0025	$2813			GOTO	L_main_0
;D_80_16F84A_Chattering_v_1_0.c,27 :: 		}//void main(void)
$0026	$2826			GOTO	$
