;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/07/16 20:55:15
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28B4			GOTO	_main
$004B	$	__pulse:
;D_85_16F84A_Remote_v_5_2.c,19 :: 		void _pulse(int num)
;D_85_16F84A_Remote_v_5_2.c,23 :: 		for(i = 0; i < num; i++)
$004B	$1303			BCF	STATUS, RP1
$004C	$1283			BCF	STATUS, RP0
$004D	$0196			CLRF	_pulse_i_L0
$004E	$0197			CLRF	_pulse_i_L0+1
$004F	$	L__pulse_0:
$004F	$3080			MOVLW	128
$0050	$0617			XORWF	_pulse_i_L0+1, 0
$0051	$00C0			MOVWF	STACK_0
$0052	$3080			MOVLW	128
$0053	$0615			XORWF	FARG__pulse+1, 0
$0054	$0240			SUBWF	STACK_0, 0
$0055	$1D03			BTFSS	STATUS, Z
$0056	$2859			GOTO	L__pulse_13
$0057	$0814			MOVF	FARG__pulse+0, 0
$0058	$0216			SUBWF	_pulse_i_L0, 0
$0059	$	L__pulse_13:
$0059	$1803			BTFSC	STATUS, C
$005A	$2882			GOTO	L__pulse_1
;D_85_16F84A_Remote_v_5_2.c,26 :: 		PORTA = 0x01; Delay_ms(1);
$005B	$3001			MOVLW	1
$005C	$0085			MOVWF	PORTA
$005D	$3007			MOVLW	7
$005E	$00CB			MOVWF	STACK_11
$005F	$30FF			MOVLW	255
$0060	$00CA			MOVWF	STACK_10
$0061	$0BCB			DECFSZ	STACK_11, F
$0062	$2864			GOTO	$+2
$0063	$2867			GOTO	$+4
$0064	$0BCA			DECFSZ	STACK_10, F
$0065	$2864			GOTO	$-1
$0066	$2861			GOTO	$-5
$0067	$3078			MOVLW	120
$0068	$00CA			MOVWF	STACK_10
$0069	$0BCA			DECFSZ	STACK_10, F
$006A	$2869			GOTO	$-1
$006B	$0000			NOP
$006C	$0000			NOP
;D_85_16F84A_Remote_v_5_2.c,28 :: 		PORTA = 0x00; Delay_ms(1);
$006D	$0185			CLRF	PORTA, 1
$006E	$3007			MOVLW	7
$006F	$00CB			MOVWF	STACK_11
$0070	$30FF			MOVLW	255
$0071	$00CA			MOVWF	STACK_10
$0072	$0BCB			DECFSZ	STACK_11, F
$0073	$2875			GOTO	$+2
$0074	$2878			GOTO	$+4
$0075	$0BCA			DECFSZ	STACK_10, F
$0076	$2875			GOTO	$-1
$0077	$2872			GOTO	$-5
$0078	$3078			MOVLW	120
$0079	$00CA			MOVWF	STACK_10
$007A	$0BCA			DECFSZ	STACK_10, F
$007B	$287A			GOTO	$-1
$007C	$0000			NOP
$007D	$0000			NOP
;D_85_16F84A_Remote_v_5_2.c,30 :: 		}
$007E	$	L__pulse_2:
;D_85_16F84A_Remote_v_5_2.c,23 :: 		for(i = 0; i < num; i++)
$007E	$0A96			INCF	_pulse_i_L0, 1
$007F	$1903			BTFSC	STATUS, Z
$0080	$0A97			INCF	_pulse_i_L0+1, 1
;D_85_16F84A_Remote_v_5_2.c,30 :: 		}
$0081	$284F			GOTO	L__pulse_0
$0082	$	L__pulse_1:
;D_85_16F84A_Remote_v_5_2.c,32 :: 		}
$0082	$0008			RETURN
$00D4	$	__while_PORTB_0x01:
;D_85_16F84A_Remote_v_5_2.c,34 :: 		void _while_PORTB_0x01(int num)
;D_85_16F84A_Remote_v_5_2.c,37 :: 		while((PORTB & 0x01) == num) //---------------------
$00D4	$	L__while_PORTB_0x01_3:
$00D4	$3001			MOVLW	1
$00D5	$1303			BCF	STATUS, RP1
$00D6	$1283			BCF	STATUS, RP0
$00D7	$0506			ANDWF	PORTB, 0
$00D8	$00C1			MOVWF	STACK_1
$00D9	$3000			MOVLW	0
$00DA	$0611			XORWF	FARG__while_PORTB_0x01+1, 0
$00DB	$1D03			BTFSS	STATUS, Z
$00DC	$28DF			GOTO	L__while_PORTB_0x01_14
$00DD	$0810			MOVF	FARG__while_PORTB_0x01+0, 0
$00DE	$0641			XORWF	STACK_1, 0
$00DF	$	L__while_PORTB_0x01_14:
$00DF	$1D03			BTFSS	STATUS, Z
$00E0	$28EC			GOTO	L__while_PORTB_0x01_4
;D_85_16F84A_Remote_v_5_2.c,40 :: 		if(TMR0 == 255)
$00E1	$0801			MOVF	TMR0, 0
$00E2	$3AFF			XORLW	255
$00E3	$1D03			BTFSS	STATUS, Z
$00E4	$28EB			GOTO	L__while_PORTB_0x01_5
;D_85_16F84A_Remote_v_5_2.c,44 :: 		_pulse(3);
$00E5	$3003			MOVLW	3
$00E6	$0094			MOVWF	FARG__pulse+0
$00E7	$3000			MOVLW	0
$00E8	$0095			MOVWF	FARG__pulse+1
$00E9	$204B			CALL	__pulse
;D_85_16F84A_Remote_v_5_2.c,47 :: 		return;
$00EA	$0008			RETURN
;D_85_16F84A_Remote_v_5_2.c,49 :: 		}
$00EB	$	L__while_PORTB_0x01_5:
;D_85_16F84A_Remote_v_5_2.c,51 :: 		}//while((PORTB & 0x01) == 0)
$00EB	$28D4			GOTO	L__while_PORTB_0x01_3
$00EC	$	L__while_PORTB_0x01_4:
;D_85_16F84A_Remote_v_5_2.c,53 :: 		return;
;D_85_16F84A_Remote_v_5_2.c,55 :: 		}
$00EC	$0008			RETURN
$0083	$	__judge_TMR_:
;D_85_16F84A_Remote_v_5_2.c,61 :: 		int _judge_TMR_(int low, int high) {
;D_85_16F84A_Remote_v_5_2.c,63 :: 		if(TMR0 < low) //---------------------
$0083	$3080			MOVLW	128
$0084	$1303			BCF	STATUS, RP1
$0085	$1283			BCF	STATUS, RP0
$0086	$00C0			MOVWF	STACK_0
$0087	$3080			MOVLW	128
$0088	$0611			XORWF	FARG__judge_TMR_+1, 0
$0089	$0240			SUBWF	STACK_0, 0
$008A	$1D03			BTFSS	STATUS, Z
$008B	$288E			GOTO	L__judge_TMR__15
$008C	$0810			MOVF	FARG__judge_TMR_+0, 0
$008D	$0201			SUBWF	TMR0, 0
$008E	$	L__judge_TMR__15:
$008E	$1803			BTFSC	STATUS, C
$008F	$289A			GOTO	L__judge_TMR__6
;D_85_16F84A_Remote_v_5_2.c,66 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$0090	$160B			BSF	INTCON, 4
;D_85_16F84A_Remote_v_5_2.c,67 :: 		INTCON |= 0x80;        // interrupt => permitted
$0091	$178B			BSF	INTCON, 7
;D_85_16F84A_Remote_v_5_2.c,74 :: 		_pulse(1);
$0092	$3001			MOVLW	1
$0093	$0094			MOVWF	FARG__pulse+0
$0094	$3000			MOVLW	0
$0095	$0095			MOVWF	FARG__pulse+1
$0096	$204B			CALL	__pulse
;D_85_16F84A_Remote_v_5_2.c,76 :: 		return false;                // return
$0097	$01C0			CLRF	STACK_0
$0098	$01C1			CLRF	STACK_0+1
$0099	$0008			RETURN
;D_85_16F84A_Remote_v_5_2.c,87 :: 		} else if (TMR0 > high) {
$009A	$	L__judge_TMR__6:
$009A	$3080			MOVLW	128
$009B	$0613			XORWF	FARG__judge_TMR_+3, 0
$009C	$00C0			MOVWF	STACK_0
$009D	$3080			MOVLW	128
$009E	$0240			SUBWF	STACK_0, 0
$009F	$1D03			BTFSS	STATUS, Z
$00A0	$28A3			GOTO	L__judge_TMR__16
$00A1	$0801			MOVF	TMR0, 0
$00A2	$0212			SUBWF	FARG__judge_TMR_+2, 0
$00A3	$	L__judge_TMR__16:
$00A3	$1803			BTFSC	STATUS, C
$00A4	$28AF			GOTO	L__judge_TMR__8
;D_85_16F84A_Remote_v_5_2.c,89 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$00A5	$160B			BSF	INTCON, 4
;D_85_16F84A_Remote_v_5_2.c,90 :: 		INTCON |= 0x80;        // interrupt => permitted
$00A6	$178B			BSF	INTCON, 7
;D_85_16F84A_Remote_v_5_2.c,93 :: 		_pulse(2);
$00A7	$3002			MOVLW	2
$00A8	$0094			MOVWF	FARG__pulse+0
$00A9	$3000			MOVLW	0
$00AA	$0095			MOVWF	FARG__pulse+1
$00AB	$204B			CALL	__pulse
;D_85_16F84A_Remote_v_5_2.c,95 :: 		return false;
$00AC	$01C0			CLRF	STACK_0
$00AD	$01C1			CLRF	STACK_0+1
$00AE	$0008			RETURN
;D_85_16F84A_Remote_v_5_2.c,97 :: 		}
$00AF	$	L__judge_TMR__8:
$00AF	$	L__judge_TMR__7:
;D_85_16F84A_Remote_v_5_2.c,99 :: 		return true;
$00AF	$3001			MOVLW	1
$00B0	$00C0			MOVWF	STACK_0
$00B1	$3000			MOVLW	0
$00B2	$00C1			MOVWF	STACK_0+1
;D_85_16F84A_Remote_v_5_2.c,101 :: 		}//int _judge_TMR_(int low, int high)
$00B3	$0008			RETURN
$00ED	$	__response:
;D_85_16F84A_Remote_v_5_2.c,103 :: 		void _response(void)
;D_85_16F84A_Remote_v_5_2.c,106 :: 		_pulse(4);
$00ED	$3004			MOVLW	4
$00EE	$1303			BCF	STATUS, RP1
$00EF	$1283			BCF	STATUS, RP0
$00F0	$0094			MOVWF	FARG__pulse+0
$00F1	$3000			MOVLW	0
$00F2	$0095			MOVWF	FARG__pulse+1
$00F3	$204B			CALL	__pulse
;D_85_16F84A_Remote_v_5_2.c,127 :: 		}
$00F4	$0008			RETURN
$0004	$	_interrupt:
$0004	$00CF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$008E			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$008D			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$008F			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0840			MOVF	STACK_0, 0
$000E	$0098			MOVWF	STSAVED_0
;D_85_16F84A_Remote_v_5_2.c,129 :: 		void interrupt(void)
;D_85_16F84A_Remote_v_5_2.c,140 :: 		INTCON &= 0x7F;  // interrupt => forbidden
$000F	$307F			MOVLW	127
$0010	$058B			ANDWF	INTCON, 1
;D_85_16F84A_Remote_v_5_2.c,141 :: 		INTCON &= 0xEF;  // INT interrupt => forbidden
$0011	$30EF			MOVLW	239
$0012	$058B			ANDWF	INTCON, 1
;D_85_16F84A_Remote_v_5_2.c,142 :: 		INTCON &= 0xFD;  // INT interrupt flag => cleared
$0013	$30FD			MOVLW	253
$0014	$058B			ANDWF	INTCON, 1
;D_85_16F84A_Remote_v_5_2.c,155 :: 		TMR0 = 0;
$0015	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_2.c,165 :: 		_while_PORTB_0x01(0);
$0016	$0190			CLRF	FARG__while_PORTB_0x01+0
$0017	$0191			CLRF	FARG__while_PORTB_0x01+1
$0018	$20D4			CALL	__while_PORTB_0x01
;D_85_16F84A_Remote_v_5_2.c,176 :: 		result = _judge_TMR_(156, 196);
$0019	$309C			MOVLW	156
$001A	$1303			BCF	STATUS, RP1
$001B	$1283			BCF	STATUS, RP0
$001C	$0090			MOVWF	FARG__judge_TMR_+0
$001D	$0191			CLRF	FARG__judge_TMR_+1
$001E	$30C4			MOVLW	196
$001F	$0092			MOVWF	FARG__judge_TMR_+2
$0020	$0193			CLRF	FARG__judge_TMR_+3
$0021	$2083			CALL	__judge_TMR_
;D_85_16F84A_Remote_v_5_2.c,178 :: 		if (result == false) {
$0022	$0840			MOVF	STACK_0, 0
$0023	$3A00			XORLW	0
$0024	$1D03			BTFSS	STATUS, Z
$0025	$2827			GOTO	L_interrupt_9
;D_85_16F84A_Remote_v_5_2.c,182 :: 		return;
$0026	$2840			GOTO	L_Interrupt_end
;D_85_16F84A_Remote_v_5_2.c,184 :: 		}
$0027	$	L_interrupt_9:
;D_85_16F84A_Remote_v_5_2.c,196 :: 		TMR0 = 0;
$0027	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_2.c,203 :: 		_while_PORTB_0x01(1);
$0028	$3001			MOVLW	1
$0029	$0090			MOVWF	FARG__while_PORTB_0x01+0
$002A	$3000			MOVLW	0
$002B	$0091			MOVWF	FARG__while_PORTB_0x01+1
$002C	$20D4			CALL	__while_PORTB_0x01
;D_85_16F84A_Remote_v_5_2.c,210 :: 		result = _judge_TMR_(68, 108);
$002D	$3044			MOVLW	68
$002E	$1303			BCF	STATUS, RP1
$002F	$1283			BCF	STATUS, RP0
$0030	$0090			MOVWF	FARG__judge_TMR_+0
$0031	$3000			MOVLW	0
$0032	$0091			MOVWF	FARG__judge_TMR_+1
$0033	$306C			MOVLW	108
$0034	$0092			MOVWF	FARG__judge_TMR_+2
$0035	$3000			MOVLW	0
$0036	$0093			MOVWF	FARG__judge_TMR_+3
$0037	$2083			CALL	__judge_TMR_
;D_85_16F84A_Remote_v_5_2.c,212 :: 		if (result == false) {
$0038	$0840			MOVF	STACK_0, 0
$0039	$3A00			XORLW	0
$003A	$1D03			BTFSS	STATUS, Z
$003B	$283D			GOTO	L_interrupt_10
;D_85_16F84A_Remote_v_5_2.c,216 :: 		return;
$003C	$2840			GOTO	L_Interrupt_end
;D_85_16F84A_Remote_v_5_2.c,218 :: 		}
$003D	$	L_interrupt_10:
;D_85_16F84A_Remote_v_5_2.c,225 :: 		_response();
$003D	$20ED			CALL	__response
;D_85_16F84A_Remote_v_5_2.c,233 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$003E	$160B			BSF	INTCON, 4
;D_85_16F84A_Remote_v_5_2.c,234 :: 		INTCON |= 0x80;
$003F	$178B			BSF	INTCON, 7
;D_85_16F84A_Remote_v_5_2.c,236 :: 		}//void interrupt(void)
$0040	$	L_Interrupt_end:
$0040	$0818			MOVF	STSAVED_0, 0
$0041	$00C0			MOVWF	STACK_0
$0042	$080F			MOVF	?savePCLATH, 0
$0043	$008A			MOVWF	PCLATH
$0044	$080D			MOVF	?saveFSR, 0
$0045	$0084			MOVWF	FSR
$0046	$0E0E			SWAPF	?saveSTATUS, 0
$0047	$0083			MOVWF	STATUS
$0048	$0ECF			SWAPF	STACK_15, 1
$0049	$0E4F			SWAPF	STACK_15, 0
$004A	$0009			RETFIE
$00F5	$	GlobalIniD_85_16F84A_Remote_v_5_2:
$00F5	$3001			MOVLW	1
$00F6	$1303			BCF	STATUS, RP1
$00F7	$1283			BCF	STATUS, RP0
$00F8	$008C			MOVWF	_LED_FLAG+0
$00F9	$0008			RETURN
$00B4	$	_main:
;D_85_16F84A_Remote_v_5_2.c,239 :: 		void main(void)
;D_85_16F84A_Remote_v_5_2.c,243 :: 		TRISA     = 0x00;
$00B4	$20F5			CALL	GlobalIniD_85_16F84A_Remote_v_5_2
$00B5	$1683			BSF	STATUS, RP0
$00B6	$0185			CLRF	TRISA, 1
;D_85_16F84A_Remote_v_5_2.c,244 :: 		PORTA     = 0x00;		//0000 0010
$00B7	$1283			BCF	STATUS, RP0
$00B8	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_2.c,246 :: 		TRISB     = 0xFF;		// Input: RB0 ~ RB7
$00B9	$30FF			MOVLW	255
$00BA	$1683			BSF	STATUS, RP0
$00BB	$0086			MOVWF	TRISB
;D_85_16F84A_Remote_v_5_2.c,248 :: 		OPTION_REG &= 0x7F;	// Pull-up => on
$00BC	$307F			MOVLW	127
$00BD	$0501			ANDWF	OPTION_REG, 0
$00BE	$00C0			MOVWF	STACK_0
$00BF	$0840			MOVF	STACK_0, 0
$00C0	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_2.c,249 :: 		OPTION_REG &= 0xBF;	// INT interrupt => by 5V ~> 0V
$00C1	$30BF			MOVLW	191
$00C2	$05C0			ANDWF	STACK_0, 1
$00C3	$0840			MOVF	STACK_0, 0
$00C4	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_2.c,251 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$00C5	$30DF			MOVLW	223
$00C6	$05C0			ANDWF	STACK_0, 1
$00C7	$0840			MOVF	STACK_0, 0
$00C8	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_2.c,252 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$00C9	$30F0			MOVLW	240
$00CA	$05C0			ANDWF	STACK_0, 1
$00CB	$0840			MOVF	STACK_0, 0
$00CC	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_2.c,253 :: 		OPTION_REG |= 0x07; // Prescaler => 1/256
$00CD	$3007			MOVLW	7
$00CE	$0440			IORWF	STACK_0, 0
$00CF	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_2.c,261 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$00D0	$160B			BSF	INTCON, 4
;D_85_16F84A_Remote_v_5_2.c,262 :: 		INTCON |= 0x80;
$00D1	$178B			BSF	INTCON, 7
;D_85_16F84A_Remote_v_5_2.c,264 :: 		while(1)
$00D2	$	L_main_11:
$00D2	$28D2			GOTO	L_main_11
;D_85_16F84A_Remote_v_5_2.c,272 :: 		}//void main(void)
$00D3	$28D3			GOTO	$
