;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/09/01 16:43:22
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$289A			GOTO	_main
$00D8	$	__pulse_Modulation:
;D-91_PIC16_color_changer_v-3.0.c,68 :: 		_pulse_Modulation(void)
;D-91_PIC16_color_changer_v-3.0.c,72 :: 		PORTA        = 0x01;   // RA0 => on
$00D8	$3001			MOVLW	1
$00D9	$1303			BCF	STATUS, RP1
$00DA	$1283			BCF	STATUS, RP0
$00DB	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-3.0.c,73 :: 		Delay_us(9);   // 8.8us
$00DC	$300E			MOVLW	14
$00DD	$00CA			MOVWF	STACK_10
$00DE	$0BCA			DECFSZ	STACK_10, F
$00DF	$28DE			GOTO	$-1
$00E0	$0000			NOP
$00E1	$0000			NOP
;D-91_PIC16_color_changer_v-3.0.c,75 :: 		PORTA        = 0x00;   // RA0 => off
$00E2	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,76 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$00E3	$301C			MOVLW	28
$00E4	$00CA			MOVWF	STACK_10
$00E5	$0BCA			DECFSZ	STACK_10, F
$00E6	$28E5			GOTO	$-1
;D-91_PIC16_color_changer_v-3.0.c,78 :: 		}
$00E7	$0008			RETURN
$00BC	$	__reader:
;D-91_PIC16_color_changer_v-3.0.c,81 :: 		_reader(void)
;D-91_PIC16_color_changer_v-3.0.c,84 :: 		TMR0     = 0;
$00BC	$1303			BCF	STATUS, RP1
$00BD	$1283			BCF	STATUS, RP0
$00BE	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.0.c,88 :: 		while(MS90)         // 9.0ms
$00BF	$	L__reader_0:
$00BF	$30B0			MOVLW	176
$00C0	$0201			SUBWF	TMR0, 0
$00C1	$1803			BTFSC	STATUS, C
$00C2	$28D1			GOTO	L__reader_1
;D-91_PIC16_color_changer_v-3.0.c,91 :: 		PORTA        = 0x01;   // RA0 => on
$00C3	$3001			MOVLW	1
$00C4	$0085			MOVWF	PORTA
;D-91_PIC16_color_changer_v-3.0.c,92 :: 		Delay_us(9);   // 8.8us
$00C5	$300E			MOVLW	14
$00C6	$00CA			MOVWF	STACK_10
$00C7	$0BCA			DECFSZ	STACK_10, F
$00C8	$28C7			GOTO	$-1
$00C9	$0000			NOP
$00CA	$0000			NOP
;D-91_PIC16_color_changer_v-3.0.c,94 :: 		PORTA        = 0x00;   // RA0 => off
$00CB	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,95 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$00CC	$301C			MOVLW	28
$00CD	$00CA			MOVWF	STACK_10
$00CE	$0BCA			DECFSZ	STACK_10, F
$00CF	$28CE			GOTO	$-1
;D-91_PIC16_color_changer_v-3.0.c,97 :: 		}
$00D0	$28BF			GOTO	L__reader_0
$00D1	$	L__reader_1:
;D-91_PIC16_color_changer_v-3.0.c,99 :: 		TMR0 = 0;
$00D1	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.0.c,100 :: 		PORTA = 0x00;
$00D2	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,102 :: 		while(MS45)       // 4.5ms
$00D3	$	L__reader_2:
$00D3	$3058			MOVLW	88
$00D4	$0201			SUBWF	TMR0, 0
$00D5	$1C03			BTFSS	STATUS, C
$00D6	$28D3			GOTO	L__reader_2
;D-91_PIC16_color_changer_v-3.0.c,106 :: 		}
$00D7	$	L__reader_3:
;D-91_PIC16_color_changer_v-3.0.c,108 :: 		}//void _reader(void)
$00D7	$0008			RETURN
$0023	$	__custom_lower:
;D-91_PIC16_color_changer_v-3.0.c,111 :: 		_custom_lower(void)
;D-91_PIC16_color_changer_v-3.0.c,115 :: 		custom_code_a = 0x0A;
$0023	$300A			MOVLW	10
$0024	$1303			BCF	STATUS, RP1
$0025	$1283			BCF	STATUS, RP0
$0026	$008C			MOVWF	_custom_code_a
;D-91_PIC16_color_changer_v-3.0.c,117 :: 		for(i = 0; i < bit_len; i++)
$0027	$018D			CLRF	_i, 1
$0028	$	L__custom_lower_4:
$0028	$080E			MOVF	_bit_len, 0
$0029	$020D			SUBWF	_i, 0
$002A	$1803			BTFSC	STATUS, C
$002B	$2851			GOTO	L__custom_lower_5
;D-91_PIC16_color_changer_v-3.0.c,125 :: 		RESET_TMR;
$002C	$0181			CLRF	TMR0, 1
;D-91_PIC16_color_changer_v-3.0.c,127 :: 		while(TMR0 < 11)	// 0.56ms
$002D	$	L__custom_lower_7:
$002D	$300B			MOVLW	11
$002E	$0201			SUBWF	TMR0, 0
$002F	$1803			BTFSC	STATUS, C
$0030	$2833			GOTO	L__custom_lower_8
;D-91_PIC16_color_changer_v-3.0.c,129 :: 		_pulse_Modulation();
$0031	$20D8			CALL	__pulse_Modulation
;D-91_PIC16_color_changer_v-3.0.c,131 :: 		}
$0032	$282D			GOTO	L__custom_lower_7
$0033	$	L__custom_lower_8:
;D-91_PIC16_color_changer_v-3.0.c,138 :: 		PORTA = 0x00;
$0033	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,140 :: 		if (((custom_code_a >> i) & 0x01) == 0)
$0034	$080D			MOVF	_i, 0
$0035	$00C1			MOVWF	STACK_1
$0036	$080C			MOVF	_custom_code_a, 0
$0037	$00C0			MOVWF	STACK_0
$0038	$0841			MOVF	STACK_1, 0
$0039	$	L__custom_lower_23:
$0039	$1903			BTFSC	STATUS, Z
$003A	$283F			GOTO	L__custom_lower_24
$003B	$0CC0			RRF	STACK_0, 1
$003C	$13C0			BCF	STACK_0, 7
$003D	$3FFF			ADDLW	255
$003E	$2839			GOTO	L__custom_lower_23
$003F	$	L__custom_lower_24:
$003F	$3001			MOVLW	1
$0040	$0540			ANDWF	STACK_0, 0
$0041	$00C1			MOVWF	STACK_1
$0042	$0841			MOVF	STACK_1, 0
$0043	$3A00			XORLW	0
$0044	$1D03			BTFSS	STATUS, Z
$0045	$284B			GOTO	L__custom_lower_9
;D-91_PIC16_color_changer_v-3.0.c,143 :: 		while(TMR0 < 22)	// 1.125ms
$0046	$	L__custom_lower_10:
$0046	$3016			MOVLW	22
$0047	$0201			SUBWF	TMR0, 0
$0048	$1C03			BTFSS	STATUS, C
$0049	$2846			GOTO	L__custom_lower_10
;D-91_PIC16_color_changer_v-3.0.c,146 :: 		}
$004A	$	L__custom_lower_11:
;D-91_PIC16_color_changer_v-3.0.c,148 :: 		} else {
$004A	$284F			GOTO	L__custom_lower_12
$004B	$	L__custom_lower_9:
;D-91_PIC16_color_changer_v-3.0.c,150 :: 		while(TMR0 < 44)	// 2.250ms
$004B	$	L__custom_lower_13:
$004B	$302C			MOVLW	44
$004C	$0201			SUBWF	TMR0, 0
$004D	$1C03			BTFSS	STATUS, C
$004E	$284B			GOTO	L__custom_lower_13
;D-91_PIC16_color_changer_v-3.0.c,153 :: 		}
$004F	$	L__custom_lower_14:
;D-91_PIC16_color_changer_v-3.0.c,155 :: 		}//if (((custom_code_a >> i) & 0x01) == 0)
$004F	$	L__custom_lower_12:
;D-91_PIC16_color_changer_v-3.0.c,157 :: 		}//for(i = 0; i < bit_len)
$004F	$	L__custom_lower_6:
;D-91_PIC16_color_changer_v-3.0.c,117 :: 		for(i = 0; i < bit_len; i++)
$004F	$0A8D			INCF	_i, 1
;D-91_PIC16_color_changer_v-3.0.c,157 :: 		}//for(i = 0; i < bit_len)
$0050	$2828			GOTO	L__custom_lower_4
$0051	$	L__custom_lower_5:
;D-91_PIC16_color_changer_v-3.0.c,159 :: 		}//_custom_lower
$0051	$0008			RETURN
$00E8	$	__pulsing_u_100:
;D-91_PIC16_color_changer_v-3.0.c,267 :: 		_pulsing_u_100()
;D-91_PIC16_color_changer_v-3.0.c,270 :: 		PORTA = 0x00;
$00E8	$1303			BCF	STATUS, RP1
$00E9	$1283			BCF	STATUS, RP0
$00EA	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,272 :: 		PORTA = 0x01; Delay_us(50);
$00EB	$3001			MOVLW	1
$00EC	$0085			MOVWF	PORTA
$00ED	$3053			MOVLW	83
$00EE	$00CA			MOVWF	STACK_10
$00EF	$0BCA			DECFSZ	STACK_10, F
$00F0	$28EF			GOTO	$-1
;D-91_PIC16_color_changer_v-3.0.c,274 :: 		PORTA = 0x00; Delay_us(50);
$00F1	$0185			CLRF	PORTA, 1
$00F2	$3053			MOVLW	83
$00F3	$00CA			MOVWF	STACK_10
$00F4	$0BCA			DECFSZ	STACK_10, F
$00F5	$28F4			GOTO	$-1
;D-91_PIC16_color_changer_v-3.0.c,276 :: 		}//_pulsing_u_100
$00F6	$0008			RETURN
$0078	$	__Delay_50ms:
;D-91_PIC16_color_changer_v-3.0.c,162 :: 		_Delay_50ms(void) {
;D-91_PIC16_color_changer_v-3.0.c,164 :: 		Delay_ms(50);
$0078	$3002			MOVLW	2
$0079	$1303			BCF	STATUS, RP1
$007A	$1283			BCF	STATUS, RP0
$007B	$00CC			MOVWF	STACK_12
$007C	$30FF			MOVLW	255
$007D	$00CB			MOVWF	STACK_11
$007E	$30FF			MOVLW	255
$007F	$00CA			MOVWF	STACK_10
$0080	$0BCC			DECFSZ	STACK_12, F
$0081	$2883			GOTO	$+2
$0082	$288A			GOTO	$+8
$0083	$0BCB			DECFSZ	STACK_11, F
$0084	$2886			GOTO	$+2
$0085	$2889			GOTO	$+4
$0086	$0BCA			DECFSZ	STACK_10, F
$0087	$2886			GOTO	$-1
$0088	$2883			GOTO	$-5
$0089	$2880			GOTO	$-9
$008A	$3046			MOVLW	70
$008B	$00CB			MOVWF	STACK_11
$008C	$30FF			MOVLW	255
$008D	$00CA			MOVWF	STACK_10
$008E	$0BCB			DECFSZ	STACK_11, F
$008F	$2891			GOTO	$+2
$0090	$2894			GOTO	$+4
$0091	$0BCA			DECFSZ	STACK_10, F
$0092	$2891			GOTO	$-1
$0093	$288E			GOTO	$-5
$0094	$30CF			MOVLW	207
$0095	$00CA			MOVWF	STACK_10
$0096	$0BCA			DECFSZ	STACK_10, F
$0097	$2896			GOTO	$-1
$0098	$0000			NOP
;D-91_PIC16_color_changer_v-3.0.c,166 :: 		}
$0099	$0008			RETURN
$0052	$	__Opearations:
;D-91_PIC16_color_changer_v-3.0.c,169 :: 		_Opearations() {
;D-91_PIC16_color_changer_v-3.0.c,171 :: 		while(PORTB_0_H) {
$0052	$	L__Opearations_15:
$0052	$3001			MOVLW	1
$0053	$1303			BCF	STATUS, RP1
$0054	$1283			BCF	STATUS, RP0
$0055	$0506			ANDWF	PORTB, 0
$0056	$00C1			MOVWF	STACK_1
$0057	$0841			MOVF	STACK_1, 0
$0058	$3A01			XORLW	1
$0059	$1D03			BTFSS	STATUS, Z
$005A	$2877			GOTO	L__Opearations_16
;D-91_PIC16_color_changer_v-3.0.c,179 :: 		if ((PORTB_1_H) && !(PORTB_2_H) && !(PORTB_3_H)) {
$005B	$3002			MOVLW	2
$005C	$0506			ANDWF	PORTB, 0
$005D	$00C1			MOVWF	STACK_1
$005E	$0841			MOVF	STACK_1, 0
$005F	$3A02			XORLW	2
$0060	$1D03			BTFSS	STATUS, Z
$0061	$2875			GOTO	L__Opearations_19
$0062	$3004			MOVLW	4
$0063	$0506			ANDWF	PORTB, 0
$0064	$00C1			MOVWF	STACK_1
$0065	$0841			MOVF	STACK_1, 0
$0066	$3A04			XORLW	4
$0067	$1903			BTFSC	STATUS, Z
$0068	$2875			GOTO	L__Opearations_19
$0069	$3008			MOVLW	8
$006A	$0506			ANDWF	PORTB, 0
$006B	$00C1			MOVWF	STACK_1
$006C	$0841			MOVF	STACK_1, 0
$006D	$3A08			XORLW	8
$006E	$1903			BTFSC	STATUS, Z
$006F	$2875			GOTO	L__Opearations_19
$0070	$	L123_ex_L__Opearations_19:
;D-91_PIC16_color_changer_v-3.0.c,181 :: 		_reader();
$0070	$20BC			CALL	__reader
;D-91_PIC16_color_changer_v-3.0.c,183 :: 		_custom_lower();
$0071	$2023			CALL	__custom_lower
;D-91_PIC16_color_changer_v-3.0.c,186 :: 		_pulsing_u_100();
$0072	$20E8			CALL	__pulsing_u_100
;D-91_PIC16_color_changer_v-3.0.c,190 :: 		_Delay_50ms();
$0073	$2078			CALL	__Delay_50ms
;D-91_PIC16_color_changer_v-3.0.c,192 :: 		} else {
$0074	$2876			GOTO	L__Opearations_20
$0075	$	L__Opearations_19:
;D-91_PIC16_color_changer_v-3.0.c,194 :: 		OUT_OFF;
$0075	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,196 :: 		}
$0076	$	L__Opearations_20:
;D-91_PIC16_color_changer_v-3.0.c,198 :: 		}//while(PORTB_0_H)
$0076	$2852			GOTO	L__Opearations_15
$0077	$	L__Opearations_16:
;D-91_PIC16_color_changer_v-3.0.c,200 :: 		}//_Opearations
$0077	$0008			RETURN
$0004	$	_interrupt:
$0004	$00CF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$0090			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$008F			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$0091			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0840			MOVF	STACK_0, 0
$000E	$0092			MOVWF	STSAVED_0
;D-91_PIC16_color_changer_v-3.0.c,202 :: 		void interrupt(void)
;D-91_PIC16_color_changer_v-3.0.c,213 :: 		INTCON &= 0x7F;  // interrupt => forbidden
$000F	$307F			MOVLW	127
$0010	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.0.c,214 :: 		INTCON &= 0xEF;  // INT interrupt => forbidden
$0011	$30EF			MOVLW	239
$0012	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.0.c,215 :: 		INTCON &= 0xFD;  // INT interrupt flag => cleared
$0013	$30FD			MOVLW	253
$0014	$058B			ANDWF	INTCON, 1
;D-91_PIC16_color_changer_v-3.0.c,217 :: 		_Opearations();
$0015	$2052			CALL	__Opearations
;D-91_PIC16_color_changer_v-3.0.c,225 :: 		INTCON |= 0x10;		  // INT interrupt => permitted
$0016	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-3.0.c,226 :: 		INTCON |= 0x80;
$0017	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-3.0.c,228 :: 		}//void interrupt(void)
$0018	$	L_Interrupt_end:
$0018	$0812			MOVF	STSAVED_0, 0
$0019	$00C0			MOVWF	STACK_0
$001A	$0811			MOVF	?savePCLATH, 0
$001B	$008A			MOVWF	PCLATH
$001C	$080F			MOVF	?saveFSR, 0
$001D	$0084			MOVWF	FSR
$001E	$0E10			SWAPF	?saveSTATUS, 0
$001F	$0083			MOVWF	STATUS
$0020	$0ECF			SWAPF	STACK_15, 1
$0021	$0E4F			SWAPF	STACK_15, 0
$0022	$0009			RETFIE
$00F7	$	GlobalIniD-91_PIC16_color_changer_v-3:
$00F7	$3004			MOVLW	4
$00F8	$1303			BCF	STATUS, RP1
$00F9	$1283			BCF	STATUS, RP0
$00FA	$008E			MOVWF	_bit_len+0
$00FB	$0008			RETURN
$009A	$	_main:
;D-91_PIC16_color_changer_v-3.0.c,231 :: 		void main(void)
;D-91_PIC16_color_changer_v-3.0.c,235 :: 		TRISA     = 0x00;
$009A	$1303			BCF	STATUS, RP1
$009B	$1683			BSF	STATUS, RP0
$009C	$0185			CLRF	TRISA, 1
;D-91_PIC16_color_changer_v-3.0.c,236 :: 		PORTA     = 0x00;		//0000 0010
$009D	$1283			BCF	STATUS, RP0
$009E	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,238 :: 		TRISB     = 0xFF;		// Input: RB0 ~ RB7
$009F	$30FF			MOVLW	255
$00A0	$1683			BSF	STATUS, RP0
$00A1	$0086			MOVWF	TRISB
;D-91_PIC16_color_changer_v-3.0.c,240 :: 		OPTION_REG &= 0x7F;	// Pull-up => on
$00A2	$307F			MOVLW	127
$00A3	$0501			ANDWF	OPTION_REG, 0
$00A4	$00C0			MOVWF	STACK_0
$00A5	$0840			MOVF	STACK_0, 0
$00A6	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.0.c,241 :: 		OPTION_REG &= 0xFF;	// INT interrupt => by 0V ~> 5V
$00A7	$30FF			MOVLW	255
$00A8	$05C0			ANDWF	STACK_0, 1
$00A9	$0840			MOVF	STACK_0, 0
$00AA	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.0.c,244 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$00AB	$30DF			MOVLW	223
$00AC	$05C0			ANDWF	STACK_0, 1
$00AD	$0840			MOVF	STACK_0, 0
$00AE	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.0.c,245 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$00AF	$30F0			MOVLW	240
$00B0	$05C0			ANDWF	STACK_0, 1
$00B1	$0840			MOVF	STACK_0, 0
$00B2	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.0.c,246 :: 		OPTION_REG |= 0x07; // Prescaler => 1/256
$00B3	$3007			MOVLW	7
$00B4	$0440			IORWF	STACK_0, 0
$00B5	$0081			MOVWF	OPTION_REG
;D-91_PIC16_color_changer_v-3.0.c,254 :: 		INTCON |= 0x10;        // INT interrupt => permitted
$00B6	$160B			BSF	INTCON, 4
;D-91_PIC16_color_changer_v-3.0.c,255 :: 		INTCON |= 0x80;
$00B7	$178B			BSF	INTCON, 7
;D-91_PIC16_color_changer_v-3.0.c,257 :: 		while(1)
$00B8	$	L_main_21:
;D-91_PIC16_color_changer_v-3.0.c,260 :: 		OUT_OFF;
$00B8	$1283			BCF	STATUS, RP0
$00B9	$0185			CLRF	PORTA, 1
;D-91_PIC16_color_changer_v-3.0.c,262 :: 		}//while(1)
$00BA	$28B8			GOTO	L_main_21
;D-91_PIC16_color_changer_v-3.0.c,264 :: 		}//void main(void)
$00BB	$28BB			GOTO	$
