;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 2014/07/22 20:45:17
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2831			GOTO	_main
$006A	$	__pulse:
;D_85_16F84A_Remote_v_5_3_2a.c,30 :: 		void _pulse(void)
;D_85_16F84A_Remote_v_5_3_2a.c,34 :: 		PORTA        = 0x01;   // RA0 => on
$006A	$3001			MOVLW	1
$006B	$1303			BCF	STATUS, RP1
$006C	$1283			BCF	STATUS, RP0
$006D	$0085			MOVWF	PORTA
;D_85_16F84A_Remote_v_5_3_2a.c,35 :: 		Delay_us(9);   // 8.8us
$006E	$300E			MOVLW	14
$006F	$00CA			MOVWF	STACK_10
$0070	$0BCA			DECFSZ	STACK_10, F
$0071	$2870			GOTO	$-1
$0072	$0000			NOP
$0073	$0000			NOP
;D_85_16F84A_Remote_v_5_3_2a.c,37 :: 		PORTA        = 0x00;   // RA0 => off
$0074	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,38 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$0075	$301C			MOVLW	28
$0076	$00CA			MOVWF	STACK_10
$0077	$0BCA			DECFSZ	STACK_10, F
$0078	$2877			GOTO	$-1
;D_85_16F84A_Remote_v_5_3_2a.c,40 :: 		}
$0079	$0008			RETURN
$004E	$	__reader:
;D_85_16F84A_Remote_v_5_3_2a.c,42 :: 		void _reader(void)
;D_85_16F84A_Remote_v_5_3_2a.c,45 :: 		TMR0     = 0;
$004E	$1303			BCF	STATUS, RP1
$004F	$1283			BCF	STATUS, RP0
$0050	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_2a.c,49 :: 		while(MS90)         // 9.0ms
$0051	$	L__reader_0:
$0051	$30B0			MOVLW	176
$0052	$0201			SUBWF	TMR0, 0
$0053	$1803			BTFSC	STATUS, C
$0054	$2863			GOTO	L__reader_1
;D_85_16F84A_Remote_v_5_3_2a.c,52 :: 		PORTA        = 0x01;   // RA0 => on
$0055	$3001			MOVLW	1
$0056	$0085			MOVWF	PORTA
;D_85_16F84A_Remote_v_5_3_2a.c,53 :: 		Delay_us(9);   // 8.8us
$0057	$300E			MOVLW	14
$0058	$00CA			MOVWF	STACK_10
$0059	$0BCA			DECFSZ	STACK_10, F
$005A	$2859			GOTO	$-1
$005B	$0000			NOP
$005C	$0000			NOP
;D_85_16F84A_Remote_v_5_3_2a.c,55 :: 		PORTA        = 0x00;   // RA0 => off
$005D	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,56 :: 		Delay_us(17);   // 26.3us - 8.8us =% 17us
$005E	$301C			MOVLW	28
$005F	$00CA			MOVWF	STACK_10
$0060	$0BCA			DECFSZ	STACK_10, F
$0061	$2860			GOTO	$-1
;D_85_16F84A_Remote_v_5_3_2a.c,58 :: 		}
$0062	$2851			GOTO	L__reader_0
$0063	$	L__reader_1:
;D_85_16F84A_Remote_v_5_3_2a.c,60 :: 		TMR0 = 0;
$0063	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_2a.c,61 :: 		PORTA = 0x00;
$0064	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,63 :: 		while(MS45)       // 4.5ms
$0065	$	L__reader_2:
$0065	$3058			MOVLW	88
$0066	$0201			SUBWF	TMR0, 0
$0067	$1C03			BTFSS	STATUS, C
$0068	$2865			GOTO	L__reader_2
;D_85_16F84A_Remote_v_5_3_2a.c,67 :: 		}
$0069	$	L__reader_3:
;D_85_16F84A_Remote_v_5_3_2a.c,69 :: 		}//void _reader(void)
$0069	$0008			RETURN
$0004	$	__custom_lower:
;D_85_16F84A_Remote_v_5_3_2a.c,71 :: 		void _custom_lower(void)
;D_85_16F84A_Remote_v_5_3_2a.c,77 :: 		for(i = 0; i < bit_len; i++)
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$018C			CLRF	_i, 1
$0007	$	L__custom_lower_4:
$0007	$080D			MOVF	_bit_len, 0
$0008	$020C			SUBWF	_i, 0
$0009	$1803			BTFSC	STATUS, C
$000A	$2830			GOTO	L__custom_lower_5
;D_85_16F84A_Remote_v_5_3_2a.c,85 :: 		RESET_TMR;
$000B	$0181			CLRF	TMR0, 1
;D_85_16F84A_Remote_v_5_3_2a.c,87 :: 		while(TMR0 < 11)	// 0.56ms
$000C	$	L__custom_lower_7:
$000C	$300B			MOVLW	11
$000D	$0201			SUBWF	TMR0, 0
$000E	$1803			BTFSC	STATUS, C
$000F	$2812			GOTO	L__custom_lower_8
;D_85_16F84A_Remote_v_5_3_2a.c,89 :: 		_pulse();
$0010	$206A			CALL	__pulse
;D_85_16F84A_Remote_v_5_3_2a.c,91 :: 		}
$0011	$280C			GOTO	L__custom_lower_7
$0012	$	L__custom_lower_8:
;D_85_16F84A_Remote_v_5_3_2a.c,98 :: 		PORTA = 0x00;
$0012	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,100 :: 		if (((custom_code_a >> i) & 0x01) == 0)
$0013	$080C			MOVF	_i, 0
$0014	$00C1			MOVWF	STACK_1
$0015	$080E			MOVF	_custom_code_a, 0
$0016	$00C0			MOVWF	STACK_0
$0017	$0841			MOVF	STACK_1, 0
$0018	$	L__custom_lower_17:
$0018	$1903			BTFSC	STATUS, Z
$0019	$281E			GOTO	L__custom_lower_18
$001A	$0CC0			RRF	STACK_0, 1
$001B	$13C0			BCF	STACK_0, 7
$001C	$3FFF			ADDLW	255
$001D	$2818			GOTO	L__custom_lower_17
$001E	$	L__custom_lower_18:
$001E	$3001			MOVLW	1
$001F	$0540			ANDWF	STACK_0, 0
$0020	$00C1			MOVWF	STACK_1
$0021	$0841			MOVF	STACK_1, 0
$0022	$3A00			XORLW	0
$0023	$1D03			BTFSS	STATUS, Z
$0024	$282A			GOTO	L__custom_lower_9
;D_85_16F84A_Remote_v_5_3_2a.c,103 :: 		while(TMR0 < 22)	// 1.125ms
$0025	$	L__custom_lower_10:
$0025	$3016			MOVLW	22
$0026	$0201			SUBWF	TMR0, 0
$0027	$1C03			BTFSS	STATUS, C
$0028	$2825			GOTO	L__custom_lower_10
;D_85_16F84A_Remote_v_5_3_2a.c,106 :: 		}
$0029	$	L__custom_lower_11:
;D_85_16F84A_Remote_v_5_3_2a.c,108 :: 		} else {
$0029	$282E			GOTO	L__custom_lower_12
$002A	$	L__custom_lower_9:
;D_85_16F84A_Remote_v_5_3_2a.c,110 :: 		while(TMR0 < 44)	// 2.250ms
$002A	$	L__custom_lower_13:
$002A	$302C			MOVLW	44
$002B	$0201			SUBWF	TMR0, 0
$002C	$1C03			BTFSS	STATUS, C
$002D	$282A			GOTO	L__custom_lower_13
;D_85_16F84A_Remote_v_5_3_2a.c,113 :: 		}
$002E	$	L__custom_lower_14:
;D_85_16F84A_Remote_v_5_3_2a.c,115 :: 		}//if (((custom_code_a >> i) & 0x01) == 0)
$002E	$	L__custom_lower_12:
;D_85_16F84A_Remote_v_5_3_2a.c,117 :: 		}//for(i = 0; i < bit_len)
$002E	$	L__custom_lower_6:
;D_85_16F84A_Remote_v_5_3_2a.c,77 :: 		for(i = 0; i < bit_len; i++)
$002E	$0A8C			INCF	_i, 1
;D_85_16F84A_Remote_v_5_3_2a.c,117 :: 		}//for(i = 0; i < bit_len)
$002F	$2807			GOTO	L__custom_lower_4
$0030	$	L__custom_lower_5:
;D_85_16F84A_Remote_v_5_3_2a.c,120 :: 		}//_custom_lower
$0030	$0008			RETURN
$007A	$	GlobalIniD_85_16F84A_Remote_v_5_3_2a:
$007A	$30FA			MOVLW	250
$007B	$1303			BCF	STATUS, RP1
$007C	$1283			BCF	STATUS, RP0
$007D	$008E			MOVWF	_custom_code_a+0
$007E	$3008			MOVLW	8
$007F	$008D			MOVWF	_bit_len+0
$0080	$0008			RETURN
$0031	$	_main:
;D_85_16F84A_Remote_v_5_3_2a.c,122 :: 		void main(void)
;D_85_16F84A_Remote_v_5_3_2a.c,129 :: 		TRISA     = 0x00;
$0031	$207A			CALL	GlobalIniD_85_16F84A_Remote_v_5_3_2a
$0032	$1683			BSF	STATUS, RP0
$0033	$0185			CLRF	TRISA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,130 :: 		PORTA     = 0x00;		//0000 0010
$0034	$1283			BCF	STATUS, RP0
$0035	$0185			CLRF	PORTA, 1
;D_85_16F84A_Remote_v_5_3_2a.c,132 :: 		TRISB     = 0x00;		// Input: RB0 ~ RB7
$0036	$1683			BSF	STATUS, RP0
$0037	$0186			CLRF	TRISB, 1
;D_85_16F84A_Remote_v_5_3_2a.c,133 :: 		PORTB     = 0x00;
$0038	$1283			BCF	STATUS, RP0
$0039	$0186			CLRF	PORTB, 1
;D_85_16F84A_Remote_v_5_3_2a.c,135 :: 		OPTION_REG &= 0xDF;	// Timer by clock
$003A	$30DF			MOVLW	223
$003B	$1683			BSF	STATUS, RP0
$003C	$0501			ANDWF	OPTION_REG, 0
$003D	$00C0			MOVWF	STACK_0
$003E	$0840			MOVF	STACK_0, 0
$003F	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_2a.c,136 :: 		OPTION_REG &= 0xF0;	// Prescaler => on
$0040	$30F0			MOVLW	240
$0041	$05C0			ANDWF	STACK_0, 1
$0042	$0840			MOVF	STACK_0, 0
$0043	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_2a.c,137 :: 		OPTION_REG |= 0x07;	// Prescaler => 1/256
$0044	$3007			MOVLW	7
$0045	$0440			IORWF	STACK_0, 0
$0046	$0081			MOVWF	OPTION_REG
;D_85_16F84A_Remote_v_5_3_2a.c,141 :: 		data_code_a   = 0x00;   // Button '+'
$0047	$018F			CLRF	_data_code_a, 1
;D_85_16F84A_Remote_v_5_3_2a.c,142 :: 		data_code_b   = ~data_code_a;
$0048	$30FF			MOVLW	255
$0049	$0090			MOVWF	_data_code_b
;D_85_16F84A_Remote_v_5_3_2a.c,144 :: 		while(1)
$004A	$	L_main_15:
;D_85_16F84A_Remote_v_5_3_2a.c,149 :: 		_reader();
$004A	$204E			CALL	__reader
;D_85_16F84A_Remote_v_5_3_2a.c,154 :: 		_custom_lower();
$004B	$2004			CALL	__custom_lower
;D_85_16F84A_Remote_v_5_3_2a.c,160 :: 		}//while(1)
$004C	$284A			GOTO	L_main_15
;D_85_16F84A_Remote_v_5_3_2a.c,162 :: 		}//void main(void)
$004D	$284D			GOTO	$
