	LIST	P=PIC16F88
	INCLUDE	P16F88.INC

	;__CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _PWRITE_ON & _CP_OFF & _BODEN_ON & _LVP_OFF & _CPD_OFF & _DEBUG_OFF
	__CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _PWRTE_ON & _CP_OFF & _BODEN_ON & _LVP_OFF & _CPD_OFF & _DEBUG_OFF

	ORG		0

MAIN
	BSF		STATUS,RP0
	CLRF	ANSEL
	CLRF	TRISB
	BCF		STATUS,RP0

LOOP
	MOVLW	02h
	MOVWF	PORTB
	
	GOTO	LOOP

	END